// Generated by https://github.com/Nats-ji/IconFontCppHeadersAndLuaTables for C and C++
// from https://github.com/FortAwesome/Font-Awesome/raw/4.x/src/icons.yml
// for use with https://github.com/FortAwesome/Font-Awesome/blob/4.x/fonts/FontAwesome.otf
#pragma once

#define ICON_MIN_FA 0xf000
#define ICON_MAX_FA 0xf2e0
#define ICON_FA_GLASS "\xef\x80\x80"	// U+f000 fa-glass, filter: martini, drink, bar, alcohol, liquor, categories: Web Application Icons
#define ICON_FA_MUSIC "\xef\x80\x81"	// U+f001 fa-music, filter: note, sound, categories: Web Application Icons
#define ICON_FA_SEARCH "\xef\x80\x82"	// U+f002 fa-search, filter: magnify, zoom, enlarge, bigger, categories: Web Application Icons
#define ICON_FA_ENVELOPE_O "\xef\x80\x83"	// U+f003 fa-envelope-o, filter: email, e-mail, letter, support, mail, message, notification, categories: Web Application Icons
#define ICON_FA_HEART "\xef\x80\x84"	// U+f004 fa-heart, filter: love, like, favorite, categories: Web Application Icons, Medical Icons
#define ICON_FA_STAR "\xef\x80\x85"	// U+f005 fa-star, filter: award, achievement, night, rating, score, favorite, categories: Web Application Icons
#define ICON_FA_STAR_O "\xef\x80\x86"	// U+f006 fa-star-o, filter: award, achievement, night, rating, score, favorite, categories: Web Application Icons
#define ICON_FA_USER "\xef\x80\x87"	// U+f007 fa-user, filter: person, man, head, profile, categories: Web Application Icons
#define ICON_FA_FILM "\xef\x80\x88"	// U+f008 fa-film, filter: movie, categories: Web Application Icons
#define ICON_FA_TH_LARGE "\xef\x80\x89"	// U+f009 fa-th-large, filter: blocks, squares, boxes, grid, categories: Text Editor Icons
#define ICON_FA_TH "\xef\x80\x8a"	// U+f00a fa-th, filter: blocks, squares, boxes, grid, categories: Text Editor Icons
#define ICON_FA_TH_LIST "\xef\x80\x8b"	// U+f00b fa-th-list, filter: ul, ol, checklist, finished, completed, done, todo, categories: Text Editor Icons
#define ICON_FA_CHECK "\xef\x80\x8c"	// U+f00c fa-check, filter: checkmark, done, todo, agree, accept, confirm, tick, ok, categories: Web Application Icons
#define ICON_FA_TIMES "\xef\x80\x8d"	// U+f00d fa-times, aliases: fa-remove, fa-close, filter: close, exit, x, cross, categories: Web Application Icons
#define ICON_FA_SEARCH_PLUS "\xef\x80\x8e"	// U+f00e fa-search-plus, filter: magnify, zoom, enlarge, bigger, categories: Web Application Icons
#define ICON_FA_SEARCH_MINUS "\xef\x80\x90"	// U+f010 fa-search-minus, filter: magnify, minify, zoom, smaller, categories: Web Application Icons
#define ICON_FA_POWER_OFF "\xef\x80\x91"	// U+f011 fa-power-off, filter: on, categories: Web Application Icons
#define ICON_FA_SIGNAL "\xef\x80\x92"	// U+f012 fa-signal, filter: graph, bars, categories: Web Application Icons
#define ICON_FA_COG "\xef\x80\x93"	// U+f013 fa-cog, aliases: fa-gear, filter: settings, categories: Web Application Icons, Spinner Icons
#define ICON_FA_TRASH_O "\xef\x80\x94"	// U+f014 fa-trash-o, filter: garbage, delete, remove, trash, hide, categories: Web Application Icons
#define ICON_FA_HOME "\xef\x80\x95"	// U+f015 fa-home, filter: main, house, categories: Web Application Icons
#define ICON_FA_FILE_O "\xef\x80\x96"	// U+f016 fa-file-o, filter: new, page, pdf, document, categories: Text Editor Icons, File Type Icons
#define ICON_FA_CLOCK_O "\xef\x80\x97"	// U+f017 fa-clock-o, filter: watch, timer, late, timestamp, categories: Web Application Icons
#define ICON_FA_ROAD "\xef\x80\x98"	// U+f018 fa-road, filter: street, categories: Web Application Icons
#define ICON_FA_DOWNLOAD "\xef\x80\x99"	// U+f019 fa-download, filter: import, categories: Web Application Icons
#define ICON_FA_ARROW_CIRCLE_O_DOWN "\xef\x80\x9a"	// U+f01a fa-arrow-circle-o-down, filter: download, categories: Directional Icons
#define ICON_FA_ARROW_CIRCLE_O_UP "\xef\x80\x9b"	// U+f01b fa-arrow-circle-o-up, categories: Directional Icons
#define ICON_FA_INBOX "\xef\x80\x9c"	// U+f01c fa-inbox, categories: Web Application Icons
#define ICON_FA_PLAY_CIRCLE_O "\xef\x80\x9d"	// U+f01d fa-play-circle-o, categories: Video Player Icons
#define ICON_FA_REPEAT "\xef\x80\x9e"	// U+f01e fa-repeat, aliases: fa-rotate-right, filter: redo, forward, categories: Text Editor Icons
#define ICON_FA_REFRESH "\xef\x80\xa1"	// U+f021 fa-refresh, filter: reload, sync, categories: Web Application Icons, Spinner Icons
#define ICON_FA_LIST_ALT "\xef\x80\xa2"	// U+f022 fa-list-alt, filter: ul, ol, checklist, finished, completed, done, todo, categories: Text Editor Icons
#define ICON_FA_LOCK "\xef\x80\xa3"	// U+f023 fa-lock, filter: protect, admin, security, categories: Web Application Icons
#define ICON_FA_FLAG "\xef\x80\xa4"	// U+f024 fa-flag, filter: report, notification, notify, categories: Web Application Icons
#define ICON_FA_HEADPHONES "\xef\x80\xa5"	// U+f025 fa-headphones, filter: sound, listen, music, audio, categories: Web Application Icons
#define ICON_FA_VOLUME_OFF "\xef\x80\xa6"	// U+f026 fa-volume-off, filter: audio, mute, sound, music, categories: Web Application Icons
#define ICON_FA_VOLUME_DOWN "\xef\x80\xa7"	// U+f027 fa-volume-down, filter: audio, lower, quieter, sound, music, categories: Web Application Icons
#define ICON_FA_VOLUME_UP "\xef\x80\xa8"	// U+f028 fa-volume-up, filter: audio, higher, louder, sound, music, categories: Web Application Icons
#define ICON_FA_QRCODE "\xef\x80\xa9"	// U+f029 fa-qrcode, filter: scan, categories: Web Application Icons
#define ICON_FA_BARCODE "\xef\x80\xaa"	// U+f02a fa-barcode, filter: scan, categories: Web Application Icons
#define ICON_FA_TAG "\xef\x80\xab"	// U+f02b fa-tag, filter: label, categories: Web Application Icons
#define ICON_FA_TAGS "\xef\x80\xac"	// U+f02c fa-tags, filter: labels, categories: Web Application Icons
#define ICON_FA_BOOK "\xef\x80\xad"	// U+f02d fa-book, filter: read, documentation, categories: Web Application Icons
#define ICON_FA_BOOKMARK "\xef\x80\xae"	// U+f02e fa-bookmark, filter: save, categories: Web Application Icons
#define ICON_FA_PRINT "\xef\x80\xaf"	// U+f02f fa-print, categories: Web Application Icons
#define ICON_FA_CAMERA "\xef\x80\xb0"	// U+f030 fa-camera, filter: photo, picture, record, categories: Web Application Icons
#define ICON_FA_FONT "\xef\x80\xb1"	// U+f031 fa-font, filter: text, categories: Text Editor Icons
#define ICON_FA_BOLD "\xef\x80\xb2"	// U+f032 fa-bold, categories: Text Editor Icons
#define ICON_FA_ITALIC "\xef\x80\xb3"	// U+f033 fa-italic, filter: italics, categories: Text Editor Icons
#define ICON_FA_TEXT_HEIGHT "\xef\x80\xb4"	// U+f034 fa-text-height, categories: Text Editor Icons
#define ICON_FA_TEXT_WIDTH "\xef\x80\xb5"	// U+f035 fa-text-width, categories: Text Editor Icons
#define ICON_FA_ALIGN_LEFT "\xef\x80\xb6"	// U+f036 fa-align-left, filter: text, categories: Text Editor Icons
#define ICON_FA_ALIGN_CENTER "\xef\x80\xb7"	// U+f037 fa-align-center, filter: middle, text, categories: Text Editor Icons
#define ICON_FA_ALIGN_RIGHT "\xef\x80\xb8"	// U+f038 fa-align-right, filter: text, categories: Text Editor Icons
#define ICON_FA_ALIGN_JUSTIFY "\xef\x80\xb9"	// U+f039 fa-align-justify, filter: text, categories: Text Editor Icons
#define ICON_FA_LIST "\xef\x80\xba"	// U+f03a fa-list, filter: ul, ol, checklist, finished, completed, done, todo, categories: Text Editor Icons
#define ICON_FA_OUTDENT "\xef\x80\xbb"	// U+f03b fa-outdent, aliases: fa-dedent, categories: Text Editor Icons
#define ICON_FA_INDENT "\xef\x80\xbc"	// U+f03c fa-indent, categories: Text Editor Icons
#define ICON_FA_VIDEO_CAMERA "\xef\x80\xbd"	// U+f03d fa-video-camera, filter: film, movie, record, categories: Web Application Icons
#define ICON_FA_PICTURE_O "\xef\x80\xbe"	// U+f03e fa-picture-o, aliases: fa-photo, fa-image, categories: Web Application Icons
#define ICON_FA_PENCIL "\xef\x81\x80"	// U+f040 fa-pencil, filter: write, edit, update, categories: Web Application Icons
#define ICON_FA_MAP_MARKER "\xef\x81\x81"	// U+f041 fa-map-marker, filter: map, pin, location, coordinates, localize, address, travel, where, place, categories: Web Application Icons
#define ICON_FA_ADJUST "\xef\x81\x82"	// U+f042 fa-adjust, filter: contrast, categories: Web Application Icons
#define ICON_FA_TINT "\xef\x81\x83"	// U+f043 fa-tint, filter: raindrop, waterdrop, drop, droplet, categories: Web Application Icons
#define ICON_FA_PENCIL_SQUARE_O "\xef\x81\x84"	// U+f044 fa-pencil-square-o, aliases: fa-edit, filter: write, edit, update, categories: Web Application Icons
#define ICON_FA_SHARE_SQUARE_O "\xef\x81\x85"	// U+f045 fa-share-square-o, filter: social, send, arrow, categories: Web Application Icons
#define ICON_FA_CHECK_SQUARE_O "\xef\x81\x86"	// U+f046 fa-check-square-o, filter: todo, done, agree, accept, confirm, ok, categories: Web Application Icons, Form Control Icons
#define ICON_FA_ARROWS "\xef\x81\x87"	// U+f047 fa-arrows, filter: move, reorder, resize, categories: Web Application Icons, Directional Icons
#define ICON_FA_STEP_BACKWARD "\xef\x81\x88"	// U+f048 fa-step-backward, filter: rewind, previous, beginning, start, first, categories: Video Player Icons
#define ICON_FA_FAST_BACKWARD "\xef\x81\x89"	// U+f049 fa-fast-backward, filter: rewind, previous, beginning, start, first, categories: Video Player Icons
#define ICON_FA_BACKWARD "\xef\x81\x8a"	// U+f04a fa-backward, filter: rewind, previous, categories: Video Player Icons
#define ICON_FA_PLAY "\xef\x81\x8b"	// U+f04b fa-play, filter: start, playing, music, sound, categories: Video Player Icons
#define ICON_FA_PAUSE "\xef\x81\x8c"	// U+f04c fa-pause, filter: wait, categories: Video Player Icons
#define ICON_FA_STOP "\xef\x81\x8d"	// U+f04d fa-stop, filter: block, box, square, categories: Video Player Icons
#define ICON_FA_FORWARD "\xef\x81\x8e"	// U+f04e fa-forward, filter: forward, next, categories: Video Player Icons
#define ICON_FA_FAST_FORWARD "\xef\x81\x90"	// U+f050 fa-fast-forward, filter: next, end, last, categories: Video Player Icons
#define ICON_FA_STEP_FORWARD "\xef\x81\x91"	// U+f051 fa-step-forward, filter: next, end, last, categories: Video Player Icons
#define ICON_FA_EJECT "\xef\x81\x92"	// U+f052 fa-eject, categories: Video Player Icons
#define ICON_FA_CHEVRON_LEFT "\xef\x81\x93"	// U+f053 fa-chevron-left, filter: bracket, previous, back, categories: Directional Icons
#define ICON_FA_CHEVRON_RIGHT "\xef\x81\x94"	// U+f054 fa-chevron-right, filter: bracket, next, forward, categories: Directional Icons
#define ICON_FA_PLUS_CIRCLE "\xef\x81\x95"	// U+f055 fa-plus-circle, filter: add, new, create, expand, categories: Web Application Icons
#define ICON_FA_MINUS_CIRCLE "\xef\x81\x96"	// U+f056 fa-minus-circle, filter: delete, remove, trash, hide, categories: Web Application Icons
#define ICON_FA_TIMES_CIRCLE "\xef\x81\x97"	// U+f057 fa-times-circle, filter: close, exit, x, categories: Web Application Icons
#define ICON_FA_CHECK_CIRCLE "\xef\x81\x98"	// U+f058 fa-check-circle, filter: todo, done, agree, accept, confirm, ok, categories: Web Application Icons
#define ICON_FA_QUESTION_CIRCLE "\xef\x81\x99"	// U+f059 fa-question-circle, filter: help, information, unknown, support, categories: Web Application Icons
#define ICON_FA_INFO_CIRCLE "\xef\x81\x9a"	// U+f05a fa-info-circle, filter: help, information, more, details, categories: Web Application Icons
#define ICON_FA_CROSSHAIRS "\xef\x81\x9b"	// U+f05b fa-crosshairs, filter: picker, categories: Web Application Icons
#define ICON_FA_TIMES_CIRCLE_O "\xef\x81\x9c"	// U+f05c fa-times-circle-o, filter: close, exit, x, categories: Web Application Icons
#define ICON_FA_CHECK_CIRCLE_O "\xef\x81\x9d"	// U+f05d fa-check-circle-o, filter: todo, done, agree, accept, confirm, ok, categories: Web Application Icons
#define ICON_FA_BAN "\xef\x81\x9e"	// U+f05e fa-ban, filter: delete, remove, trash, hide, block, stop, abort, cancel, categories: Web Application Icons
#define ICON_FA_ARROW_LEFT "\xef\x81\xa0"	// U+f060 fa-arrow-left, filter: previous, back, categories: Directional Icons
#define ICON_FA_ARROW_RIGHT "\xef\x81\xa1"	// U+f061 fa-arrow-right, filter: next, forward, categories: Directional Icons
#define ICON_FA_ARROW_UP "\xef\x81\xa2"	// U+f062 fa-arrow-up, categories: Directional Icons
#define ICON_FA_ARROW_DOWN "\xef\x81\xa3"	// U+f063 fa-arrow-down, filter: download, categories: Directional Icons
#define ICON_FA_SHARE "\xef\x81\xa4"	// U+f064 fa-share, aliases: fa-mail-forward, categories: Web Application Icons
#define ICON_FA_EXPAND "\xef\x81\xa5"	// U+f065 fa-expand, filter: enlarge, bigger, resize, categories: Video Player Icons
#define ICON_FA_COMPRESS "\xef\x81\xa6"	// U+f066 fa-compress, filter: collapse, combine, contract, merge, smaller, categories: Video Player Icons
#define ICON_FA_PLUS "\xef\x81\xa7"	// U+f067 fa-plus, filter: add, new, create, expand, categories: Web Application Icons
#define ICON_FA_MINUS "\xef\x81\xa8"	// U+f068 fa-minus, filter: hide, minify, delete, remove, trash, hide, collapse, categories: Web Application Icons
#define ICON_FA_ASTERISK "\xef\x81\xa9"	// U+f069 fa-asterisk, filter: details, categories: Web Application Icons
#define ICON_FA_EXCLAMATION_CIRCLE "\xef\x81\xaa"	// U+f06a fa-exclamation-circle, filter: warning, error, problem, notification, alert, categories: Web Application Icons
#define ICON_FA_GIFT "\xef\x81\xab"	// U+f06b fa-gift, filter: present, categories: Web Application Icons
#define ICON_FA_LEAF "\xef\x81\xac"	// U+f06c fa-leaf, filter: eco, nature, plant, categories: Web Application Icons
#define ICON_FA_FIRE "\xef\x81\xad"	// U+f06d fa-fire, filter: flame, hot, popular, categories: Web Application Icons
#define ICON_FA_EYE "\xef\x81\xae"	// U+f06e fa-eye, filter: show, visible, views, categories: Web Application Icons
#define ICON_FA_EYE_SLASH "\xef\x81\xb0"	// U+f070 fa-eye-slash, filter: toggle, show, hide, visible, visiblity, views, categories: Web Application Icons
#define ICON_FA_EXCLAMATION_TRIANGLE "\xef\x81\xb1"	// U+f071 fa-exclamation-triangle, aliases: fa-warning, filter: warning, error, problem, notification, alert, categories: Web Application Icons
#define ICON_FA_PLANE "\xef\x81\xb2"	// U+f072 fa-plane, filter: travel, trip, location, destination, airplane, fly, mode, categories: Web Application Icons, Transportation Icons
#define ICON_FA_CALENDAR "\xef\x81\xb3"	// U+f073 fa-calendar, filter: date, time, when, event, categories: Web Application Icons
#define ICON_FA_RANDOM "\xef\x81\xb4"	// U+f074 fa-random, filter: sort, shuffle, categories: Web Application Icons, Video Player Icons
#define ICON_FA_COMMENT "\xef\x81\xb5"	// U+f075 fa-comment, filter: speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation, categories: Web Application Icons
#define ICON_FA_MAGNET "\xef\x81\xb6"	// U+f076 fa-magnet, categories: Web Application Icons
#define ICON_FA_CHEVRON_UP "\xef\x81\xb7"	// U+f077 fa-chevron-up, categories: Directional Icons
#define ICON_FA_CHEVRON_DOWN "\xef\x81\xb8"	// U+f078 fa-chevron-down, categories: Directional Icons
#define ICON_FA_RETWEET "\xef\x81\xb9"	// U+f079 fa-retweet, filter: refresh, reload, share, categories: Web Application Icons
#define ICON_FA_SHOPPING_CART "\xef\x81\xba"	// U+f07a fa-shopping-cart, filter: checkout, buy, purchase, payment, categories: Web Application Icons
#define ICON_FA_FOLDER "\xef\x81\xbb"	// U+f07b fa-folder, categories: Web Application Icons
#define ICON_FA_FOLDER_OPEN "\xef\x81\xbc"	// U+f07c fa-folder-open, categories: Web Application Icons
#define ICON_FA_ARROWS_V "\xef\x81\xbd"	// U+f07d fa-arrows-v, filter: resize, categories: Web Application Icons, Directional Icons
#define ICON_FA_ARROWS_H "\xef\x81\xbe"	// U+f07e fa-arrows-h, filter: resize, categories: Web Application Icons, Directional Icons
#define ICON_FA_BAR_CHART "\xef\x82\x80"	// U+f080 fa-bar-chart, aliases: fa-bar-chart-o, filter: graph, analytics, statistics, categories: Web Application Icons, Chart Icons
#define ICON_FA_TWITTER_SQUARE "\xef\x82\x81"	// U+f081 fa-twitter-square, filter: tweet, social network, categories: Brand Icons
#define ICON_FA_FACEBOOK_SQUARE "\xef\x82\x82"	// U+f082 fa-facebook-square, filter: social network, categories: Brand Icons
#define ICON_FA_CAMERA_RETRO "\xef\x82\x83"	// U+f083 fa-camera-retro, filter: photo, picture, record, categories: Web Application Icons
#define ICON_FA_KEY "\xef\x82\x84"	// U+f084 fa-key, filter: unlock, password, categories: Web Application Icons
#define ICON_FA_COGS "\xef\x82\x85"	// U+f085 fa-cogs, aliases: fa-gears, filter: settings, categories: Web Application Icons
#define ICON_FA_COMMENTS "\xef\x82\x86"	// U+f086 fa-comments, filter: speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation, categories: Web Application Icons
#define ICON_FA_THUMBS_O_UP "\xef\x82\x87"	// U+f087 fa-thumbs-o-up, filter: like, approve, favorite, agree, hand, categories: Web Application Icons, Hand Icons
#define ICON_FA_THUMBS_O_DOWN "\xef\x82\x88"	// U+f088 fa-thumbs-o-down, filter: dislike, disapprove, disagree, hand, categories: Web Application Icons, Hand Icons
#define ICON_FA_STAR_HALF "\xef\x82\x89"	// U+f089 fa-star-half, filter: award, achievement, rating, score, categories: Web Application Icons
#define ICON_FA_HEART_O "\xef\x82\x8a"	// U+f08a fa-heart-o, filter: love, like, favorite, categories: Web Application Icons, Medical Icons
#define ICON_FA_SIGN_OUT "\xef\x82\x8b"	// U+f08b fa-sign-out, filter: log out, logout, leave, exit, arrow, categories: Web Application Icons
#define ICON_FA_LINKEDIN_SQUARE "\xef\x82\x8c"	// U+f08c fa-linkedin-square, categories: Brand Icons
#define ICON_FA_THUMB_TACK "\xef\x82\x8d"	// U+f08d fa-thumb-tack, filter: marker, pin, location, coordinates, categories: Web Application Icons
#define ICON_FA_EXTERNAL_LINK "\xef\x82\x8e"	// U+f08e fa-external-link, filter: open, new, categories: Web Application Icons
#define ICON_FA_SIGN_IN "\xef\x82\x90"	// U+f090 fa-sign-in, filter: enter, join, log in, login, sign up, sign in, signin, signup, arrow, categories: Web Application Icons
#define ICON_FA_TROPHY "\xef\x82\x91"	// U+f091 fa-trophy, filter: award, achievement, cup, winner, game, categories: Web Application Icons
#define ICON_FA_GITHUB_SQUARE "\xef\x82\x92"	// U+f092 fa-github-square, filter: octocat, categories: Brand Icons
#define ICON_FA_UPLOAD "\xef\x82\x93"	// U+f093 fa-upload, filter: import, categories: Web Application Icons
#define ICON_FA_LEMON_O "\xef\x82\x94"	// U+f094 fa-lemon-o, filter: food, categories: Web Application Icons
#define ICON_FA_PHONE "\xef\x82\x95"	// U+f095 fa-phone, filter: call, voice, number, support, earphone, telephone, categories: Web Application Icons
#define ICON_FA_SQUARE_O "\xef\x82\x96"	// U+f096 fa-square-o, filter: block, square, box, categories: Web Application Icons, Form Control Icons
#define ICON_FA_BOOKMARK_O "\xef\x82\x97"	// U+f097 fa-bookmark-o, filter: save, categories: Web Application Icons
#define ICON_FA_PHONE_SQUARE "\xef\x82\x98"	// U+f098 fa-phone-square, filter: call, voice, number, support, telephone, categories: Web Application Icons
#define ICON_FA_TWITTER "\xef\x82\x99"	// U+f099 fa-twitter, filter: tweet, social network, categories: Brand Icons
#define ICON_FA_FACEBOOK "\xef\x82\x9a"	// U+f09a fa-facebook, aliases: fa-facebook-f, filter: social network, categories: Brand Icons
#define ICON_FA_GITHUB "\xef\x82\x9b"	// U+f09b fa-github, filter: octocat, categories: Brand Icons
#define ICON_FA_UNLOCK "\xef\x82\x9c"	// U+f09c fa-unlock, filter: protect, admin, password, lock, categories: Web Application Icons
#define ICON_FA_CREDIT_CARD "\xef\x82\x9d"	// U+f09d fa-credit-card, filter: money, buy, debit, checkout, purchase, payment, categories: Web Application Icons, Payment Icons
#define ICON_FA_RSS "\xef\x82\x9e"	// U+f09e fa-rss, aliases: fa-feed, filter: blog, categories: Web Application Icons
#define ICON_FA_HDD_O "\xef\x82\xa0"	// U+f0a0 fa-hdd-o, filter: harddrive, hard drive, storage, save, categories: Web Application Icons
#define ICON_FA_BULLHORN "\xef\x82\xa1"	// U+f0a1 fa-bullhorn, filter: announcement, share, broadcast, louder, megaphone, categories: Web Application Icons
#define ICON_FA_BELL "\xef\x83\xb3"	// U+f0f3 fa-bell, filter: alert, reminder, notification, categories: Web Application Icons
#define ICON_FA_CERTIFICATE "\xef\x82\xa3"	// U+f0a3 fa-certificate, filter: badge, star, categories: Web Application Icons
#define ICON_FA_HAND_O_RIGHT "\xef\x82\xa4"	// U+f0a4 fa-hand-o-right, filter: point, right, next, forward, finger, categories: Directional Icons, Hand Icons
#define ICON_FA_HAND_O_LEFT "\xef\x82\xa5"	// U+f0a5 fa-hand-o-left, filter: point, left, previous, back, finger, categories: Directional Icons, Hand Icons
#define ICON_FA_HAND_O_UP "\xef\x82\xa6"	// U+f0a6 fa-hand-o-up, filter: point, finger, categories: Directional Icons, Hand Icons
#define ICON_FA_HAND_O_DOWN "\xef\x82\xa7"	// U+f0a7 fa-hand-o-down, filter: point, finger, categories: Directional Icons, Hand Icons
#define ICON_FA_ARROW_CIRCLE_LEFT "\xef\x82\xa8"	// U+f0a8 fa-arrow-circle-left, filter: previous, back, categories: Directional Icons
#define ICON_FA_ARROW_CIRCLE_RIGHT "\xef\x82\xa9"	// U+f0a9 fa-arrow-circle-right, filter: next, forward, categories: Directional Icons
#define ICON_FA_ARROW_CIRCLE_UP "\xef\x82\xaa"	// U+f0aa fa-arrow-circle-up, categories: Directional Icons
#define ICON_FA_ARROW_CIRCLE_DOWN "\xef\x82\xab"	// U+f0ab fa-arrow-circle-down, filter: download, categories: Directional Icons
#define ICON_FA_GLOBE "\xef\x82\xac"	// U+f0ac fa-globe, filter: world, planet, map, place, travel, earth, global, translate, all, language, localize, location, coordinates, country, categories: Web Application Icons
#define ICON_FA_WRENCH "\xef\x82\xad"	// U+f0ad fa-wrench, filter: settings, fix, update, spanner, categories: Web Application Icons
#define ICON_FA_TASKS "\xef\x82\xae"	// U+f0ae fa-tasks, filter: progress, loading, downloading, downloads, settings, categories: Web Application Icons
#define ICON_FA_FILTER "\xef\x82\xb0"	// U+f0b0 fa-filter, filter: funnel, options, categories: Web Application Icons
#define ICON_FA_BRIEFCASE "\xef\x82\xb1"	// U+f0b1 fa-briefcase, filter: work, business, office, luggage, bag, categories: Web Application Icons
#define ICON_FA_ARROWS_ALT "\xef\x82\xb2"	// U+f0b2 fa-arrows-alt, filter: expand, enlarge, fullscreen, bigger, move, reorder, resize, arrow, categories: Video Player Icons, Directional Icons
#define ICON_FA_USERS "\xef\x83\x80"	// U+f0c0 fa-users, aliases: fa-group, filter: people, profiles, persons, categories: Web Application Icons
#define ICON_FA_LINK "\xef\x83\x81"	// U+f0c1 fa-link, aliases: fa-chain, filter: chain, categories: Text Editor Icons
#define ICON_FA_CLOUD "\xef\x83\x82"	// U+f0c2 fa-cloud, filter: save, categories: Web Application Icons
#define ICON_FA_FLASK "\xef\x83\x83"	// U+f0c3 fa-flask, filter: science, beaker, experimental, labs, categories: Web Application Icons
#define ICON_FA_SCISSORS "\xef\x83\x84"	// U+f0c4 fa-scissors, aliases: fa-cut, categories: Text Editor Icons
#define ICON_FA_FILES_O "\xef\x83\x85"	// U+f0c5 fa-files-o, aliases: fa-copy, filter: duplicate, clone, copy, categories: Text Editor Icons
#define ICON_FA_PAPERCLIP "\xef\x83\x86"	// U+f0c6 fa-paperclip, filter: attachment, categories: Text Editor Icons
#define ICON_FA_FLOPPY_O "\xef\x83\x87"	// U+f0c7 fa-floppy-o, aliases: fa-save, categories: Text Editor Icons
#define ICON_FA_SQUARE "\xef\x83\x88"	// U+f0c8 fa-square, filter: block, box, categories: Web Application Icons, Form Control Icons
#define ICON_FA_BARS "\xef\x83\x89"	// U+f0c9 fa-bars, aliases: fa-navicon, fa-reorder, filter: menu, drag, reorder, settings, list, ul, ol, checklist, todo, list, hamburger, categories: Web Application Icons
#define ICON_FA_LIST_UL "\xef\x83\x8a"	// U+f0ca fa-list-ul, filter: ul, ol, checklist, todo, list, categories: Text Editor Icons
#define ICON_FA_LIST_OL "\xef\x83\x8b"	// U+f0cb fa-list-ol, filter: ul, ol, checklist, list, todo, list, numbers, categories: Text Editor Icons
#define ICON_FA_STRIKETHROUGH "\xef\x83\x8c"	// U+f0cc fa-strikethrough, categories: Text Editor Icons
#define ICON_FA_UNDERLINE "\xef\x83\x8d"	// U+f0cd fa-underline, categories: Text Editor Icons
#define ICON_FA_TABLE "\xef\x83\x8e"	// U+f0ce fa-table, filter: data, excel, spreadsheet, categories: Text Editor Icons
#define ICON_FA_MAGIC "\xef\x83\x90"	// U+f0d0 fa-magic, filter: wizard, automatic, autocomplete, categories: Web Application Icons
#define ICON_FA_TRUCK "\xef\x83\x91"	// U+f0d1 fa-truck, filter: shipping, categories: Web Application Icons, Transportation Icons
#define ICON_FA_PINTEREST "\xef\x83\x92"	// U+f0d2 fa-pinterest, categories: Brand Icons
#define ICON_FA_PINTEREST_SQUARE "\xef\x83\x93"	// U+f0d3 fa-pinterest-square, categories: Brand Icons
#define ICON_FA_GOOGLE_PLUS_SQUARE "\xef\x83\x94"	// U+f0d4 fa-google-plus-square, filter: social network, categories: Brand Icons
#define ICON_FA_GOOGLE_PLUS "\xef\x83\x95"	// U+f0d5 fa-google-plus, filter: social network, categories: Brand Icons
#define ICON_FA_MONEY "\xef\x83\x96"	// U+f0d6 fa-money, filter: cash, money, buy, checkout, purchase, payment, categories: Web Application Icons, Currency Icons
#define ICON_FA_CARET_DOWN "\xef\x83\x97"	// U+f0d7 fa-caret-down, filter: more, dropdown, menu, triangle down, arrow, categories: Directional Icons
#define ICON_FA_CARET_UP "\xef\x83\x98"	// U+f0d8 fa-caret-up, filter: triangle up, arrow, categories: Directional Icons
#define ICON_FA_CARET_LEFT "\xef\x83\x99"	// U+f0d9 fa-caret-left, filter: previous, back, triangle left, arrow, categories: Directional Icons
#define ICON_FA_CARET_RIGHT "\xef\x83\x9a"	// U+f0da fa-caret-right, filter: next, forward, triangle right, arrow, categories: Directional Icons
#define ICON_FA_COLUMNS "\xef\x83\x9b"	// U+f0db fa-columns, filter: split, panes, categories: Text Editor Icons
#define ICON_FA_SORT "\xef\x83\x9c"	// U+f0dc fa-sort, aliases: fa-unsorted, filter: order, categories: Web Application Icons
#define ICON_FA_SORT_DESC "\xef\x83\x9d"	// U+f0dd fa-sort-desc, aliases: fa-sort-down, filter: dropdown, more, menu, arrow, categories: Web Application Icons
#define ICON_FA_SORT_ASC "\xef\x83\x9e"	// U+f0de fa-sort-asc, aliases: fa-sort-up, filter: arrow, categories: Web Application Icons
#define ICON_FA_ENVELOPE "\xef\x83\xa0"	// U+f0e0 fa-envelope, filter: email, e-mail, letter, support, mail, message, notification, categories: Web Application Icons
#define ICON_FA_LINKEDIN "\xef\x83\xa1"	// U+f0e1 fa-linkedin, categories: Brand Icons
#define ICON_FA_UNDO "\xef\x83\xa2"	// U+f0e2 fa-undo, aliases: fa-rotate-left, filter: back, categories: Text Editor Icons
#define ICON_FA_GAVEL "\xef\x83\xa3"	// U+f0e3 fa-gavel, aliases: fa-legal, filter: judge, lawyer, opinion, categories: Web Application Icons
#define ICON_FA_TACHOMETER "\xef\x83\xa4"	// U+f0e4 fa-tachometer, aliases: fa-dashboard, filter: speedometer, fast, categories: Web Application Icons
#define ICON_FA_COMMENT_O "\xef\x83\xa5"	// U+f0e5 fa-comment-o, filter: speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation, categories: Web Application Icons
#define ICON_FA_COMMENTS_O "\xef\x83\xa6"	// U+f0e6 fa-comments-o, filter: speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation, categories: Web Application Icons
#define ICON_FA_BOLT "\xef\x83\xa7"	// U+f0e7 fa-bolt, aliases: fa-flash, filter: lightning, weather, categories: Web Application Icons
#define ICON_FA_SITEMAP "\xef\x83\xa8"	// U+f0e8 fa-sitemap, filter: directory, hierarchy, organization, categories: Web Application Icons
#define ICON_FA_UMBRELLA "\xef\x83\xa9"	// U+f0e9 fa-umbrella, categories: Web Application Icons
#define ICON_FA_CLIPBOARD "\xef\x83\xaa"	// U+f0ea fa-clipboard, aliases: fa-paste, filter: copy, categories: Text Editor Icons
#define ICON_FA_LIGHTBULB_O "\xef\x83\xab"	// U+f0eb fa-lightbulb-o, filter: idea, inspiration, categories: Web Application Icons
#define ICON_FA_EXCHANGE "\xef\x83\xac"	// U+f0ec fa-exchange, filter: transfer, arrows, arrow, categories: Web Application Icons, Directional Icons
#define ICON_FA_CLOUD_DOWNLOAD "\xef\x83\xad"	// U+f0ed fa-cloud-download, filter: import, categories: Web Application Icons
#define ICON_FA_CLOUD_UPLOAD "\xef\x83\xae"	// U+f0ee fa-cloud-upload, filter: import, categories: Web Application Icons
#define ICON_FA_USER_MD "\xef\x83\xb0"	// U+f0f0 fa-user-md, filter: doctor, profile, medical, nurse, categories: Medical Icons
#define ICON_FA_STETHOSCOPE "\xef\x83\xb1"	// U+f0f1 fa-stethoscope, categories: Medical Icons
#define ICON_FA_SUITCASE "\xef\x83\xb2"	// U+f0f2 fa-suitcase, filter: trip, luggage, travel, move, baggage, categories: Web Application Icons
#define ICON_FA_BELL_O "\xef\x82\xa2"	// U+f0a2 fa-bell-o, filter: alert, reminder, notification, categories: Web Application Icons
#define ICON_FA_COFFEE "\xef\x83\xb4"	// U+f0f4 fa-coffee, filter: morning, mug, breakfast, tea, drink, cafe, categories: Web Application Icons
#define ICON_FA_CUTLERY "\xef\x83\xb5"	// U+f0f5 fa-cutlery, filter: food, restaurant, spoon, knife, dinner, eat, categories: Web Application Icons
#define ICON_FA_FILE_TEXT_O "\xef\x83\xb6"	// U+f0f6 fa-file-text-o, filter: new, page, pdf, document, categories: Text Editor Icons, File Type Icons
#define ICON_FA_BUILDING_O "\xef\x83\xb7"	// U+f0f7 fa-building-o, filter: work, business, apartment, office, company, categories: Web Application Icons
#define ICON_FA_HOSPITAL_O "\xef\x83\xb8"	// U+f0f8 fa-hospital-o, filter: building, categories: Medical Icons
#define ICON_FA_AMBULANCE "\xef\x83\xb9"	// U+f0f9 fa-ambulance, filter: vehicle, support, help, categories: Medical Icons, Transportation Icons
#define ICON_FA_MEDKIT "\xef\x83\xba"	// U+f0fa fa-medkit, filter: first aid, firstaid, help, support, health, categories: Medical Icons
#define ICON_FA_FIGHTER_JET "\xef\x83\xbb"	// U+f0fb fa-fighter-jet, filter: fly, plane, airplane, quick, fast, travel, categories: Web Application Icons, Transportation Icons
#define ICON_FA_BEER "\xef\x83\xbc"	// U+f0fc fa-beer, filter: alcohol, stein, drink, mug, bar, liquor, categories: Web Application Icons
#define ICON_FA_H_SQUARE "\xef\x83\xbd"	// U+f0fd fa-h-square, filter: hospital, hotel, categories: Medical Icons
#define ICON_FA_PLUS_SQUARE "\xef\x83\xbe"	// U+f0fe fa-plus-square, filter: add, new, create, expand, categories: Medical Icons, Web Application Icons, Form Control Icons
#define ICON_FA_ANGLE_DOUBLE_LEFT "\xef\x84\x80"	// U+f100 fa-angle-double-left, filter: laquo, quote, previous, back, arrows, categories: Directional Icons
#define ICON_FA_ANGLE_DOUBLE_RIGHT "\xef\x84\x81"	// U+f101 fa-angle-double-right, filter: raquo, quote, next, forward, arrows, categories: Directional Icons
#define ICON_FA_ANGLE_DOUBLE_UP "\xef\x84\x82"	// U+f102 fa-angle-double-up, filter: arrows, categories: Directional Icons
#define ICON_FA_ANGLE_DOUBLE_DOWN "\xef\x84\x83"	// U+f103 fa-angle-double-down, filter: arrows, categories: Directional Icons
#define ICON_FA_ANGLE_LEFT "\xef\x84\x84"	// U+f104 fa-angle-left, filter: previous, back, arrow, categories: Directional Icons
#define ICON_FA_ANGLE_RIGHT "\xef\x84\x85"	// U+f105 fa-angle-right, filter: next, forward, arrow, categories: Directional Icons
#define ICON_FA_ANGLE_UP "\xef\x84\x86"	// U+f106 fa-angle-up, filter: arrow, categories: Directional Icons
#define ICON_FA_ANGLE_DOWN "\xef\x84\x87"	// U+f107 fa-angle-down, filter: arrow, categories: Directional Icons
#define ICON_FA_DESKTOP "\xef\x84\x88"	// U+f108 fa-desktop, filter: monitor, screen, desktop, computer, demo, device, categories: Web Application Icons
#define ICON_FA_LAPTOP "\xef\x84\x89"	// U+f109 fa-laptop, filter: demo, computer, device, categories: Web Application Icons
#define ICON_FA_TABLET "\xef\x84\x8a"	// U+f10a fa-tablet, filter: ipad, device, categories: Web Application Icons
#define ICON_FA_MOBILE "\xef\x84\x8b"	// U+f10b fa-mobile, aliases: fa-mobile-phone, filter: cell phone, cellphone, text, call, iphone, number, telephone, categories: Web Application Icons
#define ICON_FA_CIRCLE_O "\xef\x84\x8c"	// U+f10c fa-circle-o, categories: Web Application Icons, Form Control Icons
#define ICON_FA_QUOTE_LEFT "\xef\x84\x8d"	// U+f10d fa-quote-left, categories: Web Application Icons
#define ICON_FA_QUOTE_RIGHT "\xef\x84\x8e"	// U+f10e fa-quote-right, categories: Web Application Icons
#define ICON_FA_SPINNER "\xef\x84\x90"	// U+f110 fa-spinner, filter: loading, progress, categories: Web Application Icons, Spinner Icons
#define ICON_FA_CIRCLE "\xef\x84\x91"	// U+f111 fa-circle, filter: dot, notification, categories: Web Application Icons, Form Control Icons
#define ICON_FA_REPLY "\xef\x84\x92"	// U+f112 fa-reply, aliases: fa-mail-reply, categories: Web Application Icons
#define ICON_FA_GITHUB_ALT "\xef\x84\x93"	// U+f113 fa-github-alt, filter: octocat, categories: Brand Icons
#define ICON_FA_FOLDER_O "\xef\x84\x94"	// U+f114 fa-folder-o, categories: Web Application Icons
#define ICON_FA_FOLDER_OPEN_O "\xef\x84\x95"	// U+f115 fa-folder-open-o, categories: Web Application Icons
#define ICON_FA_SMILE_O "\xef\x84\x98"	// U+f118 fa-smile-o, filter: face, emoticon, happy, approve, satisfied, rating, categories: Web Application Icons
#define ICON_FA_FROWN_O "\xef\x84\x99"	// U+f119 fa-frown-o, filter: face, emoticon, sad, disapprove, rating, categories: Web Application Icons
#define ICON_FA_MEH_O "\xef\x84\x9a"	// U+f11a fa-meh-o, filter: face, emoticon, rating, neutral, categories: Web Application Icons
#define ICON_FA_GAMEPAD "\xef\x84\x9b"	// U+f11b fa-gamepad, filter: controller, categories: Web Application Icons
#define ICON_FA_KEYBOARD_O "\xef\x84\x9c"	// U+f11c fa-keyboard-o, filter: type, input, categories: Web Application Icons
#define ICON_FA_FLAG_O "\xef\x84\x9d"	// U+f11d fa-flag-o, filter: report, notification, categories: Web Application Icons
#define ICON_FA_FLAG_CHECKERED "\xef\x84\x9e"	// U+f11e fa-flag-checkered, filter: report, notification, notify, categories: Web Application Icons
#define ICON_FA_TERMINAL "\xef\x84\xa0"	// U+f120 fa-terminal, filter: command, prompt, code, categories: Web Application Icons
#define ICON_FA_CODE "\xef\x84\xa1"	// U+f121 fa-code, filter: html, brackets, categories: Web Application Icons
#define ICON_FA_REPLY_ALL "\xef\x84\xa2"	// U+f122 fa-reply-all, aliases: fa-mail-reply-all, categories: Web Application Icons
#define ICON_FA_STAR_HALF_O "\xef\x84\xa3"	// U+f123 fa-star-half-o, aliases: fa-star-half-empty, fa-star-half-full, filter: award, achievement, rating, score, categories: Web Application Icons
#define ICON_FA_LOCATION_ARROW "\xef\x84\xa4"	// U+f124 fa-location-arrow, filter: map, coordinates, location, address, place, where, categories: Web Application Icons
#define ICON_FA_CROP "\xef\x84\xa5"	// U+f125 fa-crop, categories: Web Application Icons
#define ICON_FA_CODE_FORK "\xef\x84\xa6"	// U+f126 fa-code-fork, filter: git, fork, vcs, svn, github, rebase, version, merge, categories: Web Application Icons
#define ICON_FA_CHAIN_BROKEN "\xef\x84\xa7"	// U+f127 fa-chain-broken, aliases: fa-unlink, filter: remove, categories: Text Editor Icons
#define ICON_FA_QUESTION "\xef\x84\xa8"	// U+f128 fa-question, filter: help, information, unknown, support, categories: Web Application Icons
#define ICON_FA_INFO "\xef\x84\xa9"	// U+f129 fa-info, filter: help, information, more, details, categories: Web Application Icons
#define ICON_FA_EXCLAMATION "\xef\x84\xaa"	// U+f12a fa-exclamation, filter: warning, error, problem, notification, notify, alert, categories: Web Application Icons
#define ICON_FA_SUPERSCRIPT "\xef\x84\xab"	// U+f12b fa-superscript, filter: exponential, categories: Text Editor Icons
#define ICON_FA_SUBSCRIPT "\xef\x84\xac"	// U+f12c fa-subscript, categories: Text Editor Icons
#define ICON_FA_ERASER "\xef\x84\xad"	// U+f12d fa-eraser, filter: remove, delete, categories: Text Editor Icons, Web Application Icons
#define ICON_FA_PUZZLE_PIECE "\xef\x84\xae"	// U+f12e fa-puzzle-piece, filter: addon, add-on, section, categories: Web Application Icons
#define ICON_FA_MICROPHONE "\xef\x84\xb0"	// U+f130 fa-microphone, filter: record, voice, sound, categories: Web Application Icons
#define ICON_FA_MICROPHONE_SLASH "\xef\x84\xb1"	// U+f131 fa-microphone-slash, filter: record, voice, sound, mute, categories: Web Application Icons
#define ICON_FA_SHIELD "\xef\x84\xb2"	// U+f132 fa-shield, filter: award, achievement, security, winner, categories: Web Application Icons
#define ICON_FA_CALENDAR_O "\xef\x84\xb3"	// U+f133 fa-calendar-o, filter: date, time, when, event, categories: Web Application Icons
#define ICON_FA_FIRE_EXTINGUISHER "\xef\x84\xb4"	// U+f134 fa-fire-extinguisher, categories: Web Application Icons
#define ICON_FA_ROCKET "\xef\x84\xb5"	// U+f135 fa-rocket, filter: app, categories: Web Application Icons, Transportation Icons
#define ICON_FA_MAXCDN "\xef\x84\xb6"	// U+f136 fa-maxcdn, categories: Brand Icons
#define ICON_FA_CHEVRON_CIRCLE_LEFT "\xef\x84\xb7"	// U+f137 fa-chevron-circle-left, filter: previous, back, arrow, categories: Directional Icons
#define ICON_FA_CHEVRON_CIRCLE_RIGHT "\xef\x84\xb8"	// U+f138 fa-chevron-circle-right, filter: next, forward, arrow, categories: Directional Icons
#define ICON_FA_CHEVRON_CIRCLE_UP "\xef\x84\xb9"	// U+f139 fa-chevron-circle-up, filter: arrow, categories: Directional Icons
#define ICON_FA_CHEVRON_CIRCLE_DOWN "\xef\x84\xba"	// U+f13a fa-chevron-circle-down, filter: more, dropdown, menu, arrow, categories: Directional Icons
#define ICON_FA_HTML5 "\xef\x84\xbb"	// U+f13b fa-html5, categories: Brand Icons
#define ICON_FA_CSS3 "\xef\x84\xbc"	// U+f13c fa-css3, filter: code, categories: Brand Icons
#define ICON_FA_ANCHOR "\xef\x84\xbd"	// U+f13d fa-anchor, filter: link, categories: Web Application Icons
#define ICON_FA_UNLOCK_ALT "\xef\x84\xbe"	// U+f13e fa-unlock-alt, filter: protect, admin, password, lock, categories: Web Application Icons
#define ICON_FA_BULLSEYE "\xef\x85\x80"	// U+f140 fa-bullseye, filter: target, categories: Web Application Icons
#define ICON_FA_ELLIPSIS_H "\xef\x85\x81"	// U+f141 fa-ellipsis-h, filter: dots, categories: Web Application Icons
#define ICON_FA_ELLIPSIS_V "\xef\x85\x82"	// U+f142 fa-ellipsis-v, filter: dots, categories: Web Application Icons
#define ICON_FA_RSS_SQUARE "\xef\x85\x83"	// U+f143 fa-rss-square, filter: feed, blog, categories: Web Application Icons
#define ICON_FA_PLAY_CIRCLE "\xef\x85\x84"	// U+f144 fa-play-circle, filter: start, playing, categories: Video Player Icons
#define ICON_FA_TICKET "\xef\x85\x85"	// U+f145 fa-ticket, filter: movie, pass, support, categories: Web Application Icons
#define ICON_FA_MINUS_SQUARE "\xef\x85\x86"	// U+f146 fa-minus-square, filter: hide, minify, delete, remove, trash, hide, collapse, categories: Web Application Icons, Form Control Icons
#define ICON_FA_MINUS_SQUARE_O "\xef\x85\x87"	// U+f147 fa-minus-square-o, filter: hide, minify, delete, remove, trash, hide, collapse, categories: Web Application Icons, Form Control Icons
#define ICON_FA_LEVEL_UP "\xef\x85\x88"	// U+f148 fa-level-up, filter: arrow, categories: Web Application Icons
#define ICON_FA_LEVEL_DOWN "\xef\x85\x89"	// U+f149 fa-level-down, filter: arrow, categories: Web Application Icons
#define ICON_FA_CHECK_SQUARE "\xef\x85\x8a"	// U+f14a fa-check-square, filter: checkmark, done, todo, agree, accept, confirm, ok, categories: Web Application Icons, Form Control Icons
#define ICON_FA_PENCIL_SQUARE "\xef\x85\x8b"	// U+f14b fa-pencil-square, filter: write, edit, update, categories: Web Application Icons
#define ICON_FA_EXTERNAL_LINK_SQUARE "\xef\x85\x8c"	// U+f14c fa-external-link-square, filter: open, new, categories: Web Application Icons
#define ICON_FA_SHARE_SQUARE "\xef\x85\x8d"	// U+f14d fa-share-square, filter: social, send, categories: Web Application Icons
#define ICON_FA_COMPASS "\xef\x85\x8e"	// U+f14e fa-compass, filter: safari, directory, menu, location, categories: Web Application Icons
#define ICON_FA_CARET_SQUARE_O_DOWN "\xef\x85\x90"	// U+f150 fa-caret-square-o-down, aliases: fa-toggle-down, filter: more, dropdown, menu, categories: Web Application Icons, Directional Icons
#define ICON_FA_CARET_SQUARE_O_UP "\xef\x85\x91"	// U+f151 fa-caret-square-o-up, aliases: fa-toggle-up, categories: Web Application Icons, Directional Icons
#define ICON_FA_CARET_SQUARE_O_RIGHT "\xef\x85\x92"	// U+f152 fa-caret-square-o-right, aliases: fa-toggle-right, filter: next, forward, categories: Web Application Icons, Directional Icons
#define ICON_FA_EUR "\xef\x85\x93"	// U+f153 fa-eur, aliases: fa-euro, categories: Currency Icons
#define ICON_FA_GBP "\xef\x85\x94"	// U+f154 fa-gbp, categories: Currency Icons
#define ICON_FA_USD "\xef\x85\x95"	// U+f155 fa-usd, aliases: fa-dollar, categories: Currency Icons
#define ICON_FA_INR "\xef\x85\x96"	// U+f156 fa-inr, aliases: fa-rupee, categories: Currency Icons
#define ICON_FA_JPY "\xef\x85\x97"	// U+f157 fa-jpy, aliases: fa-cny, fa-rmb, fa-yen, categories: Currency Icons
#define ICON_FA_RUB "\xef\x85\x98"	// U+f158 fa-rub, aliases: fa-ruble, fa-rouble, categories: Currency Icons
#define ICON_FA_KRW "\xef\x85\x99"	// U+f159 fa-krw, aliases: fa-won, categories: Currency Icons
#define ICON_FA_BTC "\xef\x85\x9a"	// U+f15a fa-btc, aliases: fa-bitcoin, categories: Currency Icons, Brand Icons
#define ICON_FA_FILE "\xef\x85\x9b"	// U+f15b fa-file, filter: new, page, pdf, document, categories: Text Editor Icons, File Type Icons
#define ICON_FA_FILE_TEXT "\xef\x85\x9c"	// U+f15c fa-file-text, filter: new, page, pdf, document, categories: Text Editor Icons, File Type Icons
#define ICON_FA_SORT_ALPHA_ASC "\xef\x85\x9d"	// U+f15d fa-sort-alpha-asc, categories: Web Application Icons
#define ICON_FA_SORT_ALPHA_DESC "\xef\x85\x9e"	// U+f15e fa-sort-alpha-desc, categories: Web Application Icons
#define ICON_FA_SORT_AMOUNT_ASC "\xef\x85\xa0"	// U+f160 fa-sort-amount-asc, categories: Web Application Icons
#define ICON_FA_SORT_AMOUNT_DESC "\xef\x85\xa1"	// U+f161 fa-sort-amount-desc, categories: Web Application Icons
#define ICON_FA_SORT_NUMERIC_ASC "\xef\x85\xa2"	// U+f162 fa-sort-numeric-asc, filter: numbers, categories: Web Application Icons
#define ICON_FA_SORT_NUMERIC_DESC "\xef\x85\xa3"	// U+f163 fa-sort-numeric-desc, filter: numbers, categories: Web Application Icons
#define ICON_FA_THUMBS_UP "\xef\x85\xa4"	// U+f164 fa-thumbs-up, filter: like, favorite, approve, agree, hand, categories: Web Application Icons, Hand Icons
#define ICON_FA_THUMBS_DOWN "\xef\x85\xa5"	// U+f165 fa-thumbs-down, filter: dislike, disapprove, disagree, hand, categories: Web Application Icons, Hand Icons
#define ICON_FA_YOUTUBE_SQUARE "\xef\x85\xa6"	// U+f166 fa-youtube-square, filter: video, film, categories: Brand Icons
#define ICON_FA_YOUTUBE "\xef\x85\xa7"	// U+f167 fa-youtube, filter: video, film, categories: Brand Icons
#define ICON_FA_XING "\xef\x85\xa8"	// U+f168 fa-xing, categories: Brand Icons
#define ICON_FA_XING_SQUARE "\xef\x85\xa9"	// U+f169 fa-xing-square, categories: Brand Icons
#define ICON_FA_YOUTUBE_PLAY "\xef\x85\xaa"	// U+f16a fa-youtube-play, filter: start, playing, categories: Brand Icons, Video Player Icons
#define ICON_FA_DROPBOX "\xef\x85\xab"	// U+f16b fa-dropbox, categories: Brand Icons
#define ICON_FA_STACK_OVERFLOW "\xef\x85\xac"	// U+f16c fa-stack-overflow, categories: Brand Icons
#define ICON_FA_INSTAGRAM "\xef\x85\xad"	// U+f16d fa-instagram, categories: Brand Icons
#define ICON_FA_FLICKR "\xef\x85\xae"	// U+f16e fa-flickr, categories: Brand Icons
#define ICON_FA_ADN "\xef\x85\xb0"	// U+f170 fa-adn, categories: Brand Icons
#define ICON_FA_BITBUCKET "\xef\x85\xb1"	// U+f171 fa-bitbucket, filter: git, categories: Brand Icons
#define ICON_FA_BITBUCKET_SQUARE "\xef\x85\xb2"	// U+f172 fa-bitbucket-square, filter: git, categories: Brand Icons
#define ICON_FA_TUMBLR "\xef\x85\xb3"	// U+f173 fa-tumblr, categories: Brand Icons
#define ICON_FA_TUMBLR_SQUARE "\xef\x85\xb4"	// U+f174 fa-tumblr-square, categories: Brand Icons
#define ICON_FA_LONG_ARROW_DOWN "\xef\x85\xb5"	// U+f175 fa-long-arrow-down, categories: Directional Icons
#define ICON_FA_LONG_ARROW_UP "\xef\x85\xb6"	// U+f176 fa-long-arrow-up, categories: Directional Icons
#define ICON_FA_LONG_ARROW_LEFT "\xef\x85\xb7"	// U+f177 fa-long-arrow-left, filter: previous, back, categories: Directional Icons
#define ICON_FA_LONG_ARROW_RIGHT "\xef\x85\xb8"	// U+f178 fa-long-arrow-right, categories: Directional Icons
#define ICON_FA_APPLE "\xef\x85\xb9"	// U+f179 fa-apple, filter: osx, food, categories: Brand Icons
#define ICON_FA_WINDOWS "\xef\x85\xba"	// U+f17a fa-windows, filter: microsoft, categories: Brand Icons
#define ICON_FA_ANDROID "\xef\x85\xbb"	// U+f17b fa-android, filter: robot, categories: Brand Icons
#define ICON_FA_LINUX "\xef\x85\xbc"	// U+f17c fa-linux, filter: tux, categories: Brand Icons
#define ICON_FA_DRIBBBLE "\xef\x85\xbd"	// U+f17d fa-dribbble, categories: Brand Icons
#define ICON_FA_SKYPE "\xef\x85\xbe"	// U+f17e fa-skype, categories: Brand Icons
#define ICON_FA_FOURSQUARE "\xef\x86\x80"	// U+f180 fa-foursquare, categories: Brand Icons
#define ICON_FA_TRELLO "\xef\x86\x81"	// U+f181 fa-trello, categories: Brand Icons
#define ICON_FA_FEMALE "\xef\x86\x82"	// U+f182 fa-female, filter: woman, user, person, profile, categories: Web Application Icons
#define ICON_FA_MALE "\xef\x86\x83"	// U+f183 fa-male, filter: man, user, person, profile, categories: Web Application Icons
#define ICON_FA_GRATIPAY "\xef\x86\x84"	// U+f184 fa-gratipay, aliases: fa-gittip, filter: heart, like, favorite, love, categories: Brand Icons
#define ICON_FA_SUN_O "\xef\x86\x85"	// U+f185 fa-sun-o, filter: weather, contrast, lighter, brighten, day, categories: Web Application Icons
#define ICON_FA_MOON_O "\xef\x86\x86"	// U+f186 fa-moon-o, filter: night, darker, contrast, categories: Web Application Icons
#define ICON_FA_ARCHIVE "\xef\x86\x87"	// U+f187 fa-archive, filter: box, storage, categories: Web Application Icons
#define ICON_FA_BUG "\xef\x86\x88"	// U+f188 fa-bug, filter: report, insect, categories: Web Application Icons
#define ICON_FA_VK "\xef\x86\x89"	// U+f189 fa-vk, categories: Brand Icons
#define ICON_FA_WEIBO "\xef\x86\x8a"	// U+f18a fa-weibo, categories: Brand Icons
#define ICON_FA_RENREN "\xef\x86\x8b"	// U+f18b fa-renren, categories: Brand Icons
#define ICON_FA_PAGELINES "\xef\x86\x8c"	// U+f18c fa-pagelines, filter: leaf, leaves, tree, plant, eco, nature, categories: Brand Icons
#define ICON_FA_STACK_EXCHANGE "\xef\x86\x8d"	// U+f18d fa-stack-exchange, categories: Brand Icons
#define ICON_FA_ARROW_CIRCLE_O_RIGHT "\xef\x86\x8e"	// U+f18e fa-arrow-circle-o-right, filter: next, forward, categories: Directional Icons
#define ICON_FA_ARROW_CIRCLE_O_LEFT "\xef\x86\x90"	// U+f190 fa-arrow-circle-o-left, filter: previous, back, categories: Directional Icons
#define ICON_FA_CARET_SQUARE_O_LEFT "\xef\x86\x91"	// U+f191 fa-caret-square-o-left, aliases: fa-toggle-left, filter: previous, back, categories: Web Application Icons, Directional Icons
#define ICON_FA_DOT_CIRCLE_O "\xef\x86\x92"	// U+f192 fa-dot-circle-o, filter: target, bullseye, notification, categories: Web Application Icons, Form Control Icons
#define ICON_FA_WHEELCHAIR "\xef\x86\x93"	// U+f193 fa-wheelchair, filter: handicap, person, categories: Web Application Icons, Medical Icons, Transportation Icons, Accessibility Icons
#define ICON_FA_VIMEO_SQUARE "\xef\x86\x94"	// U+f194 fa-vimeo-square, categories: Brand Icons
#define ICON_FA_TRY "\xef\x86\x95"	// U+f195 fa-try, aliases: fa-turkish-lira, categories: Currency Icons
#define ICON_FA_PLUS_SQUARE_O "\xef\x86\x96"	// U+f196 fa-plus-square-o, filter: add, new, create, expand, categories: Web Application Icons, Form Control Icons
#define ICON_FA_SPACE_SHUTTLE "\xef\x86\x97"	// U+f197 fa-space-shuttle, categories: Web Application Icons, Transportation Icons
#define ICON_FA_SLACK "\xef\x86\x98"	// U+f198 fa-slack, filter: hashtag, anchor, hash, categories: Brand Icons
#define ICON_FA_ENVELOPE_SQUARE "\xef\x86\x99"	// U+f199 fa-envelope-square, filter: email, e-mail, letter, support, mail, message, notification, categories: Web Application Icons
#define ICON_FA_WORDPRESS "\xef\x86\x9a"	// U+f19a fa-wordpress, categories: Brand Icons
#define ICON_FA_OPENID "\xef\x86\x9b"	// U+f19b fa-openid, categories: Brand Icons
#define ICON_FA_UNIVERSITY "\xef\x86\x9c"	// U+f19c fa-university, aliases: fa-institution, fa-bank, categories: Web Application Icons
#define ICON_FA_GRADUATION_CAP "\xef\x86\x9d"	// U+f19d fa-graduation-cap, aliases: fa-mortar-board, filter: learning, school, student, categories: Web Application Icons
#define ICON_FA_YAHOO "\xef\x86\x9e"	// U+f19e fa-yahoo, categories: Brand Icons
#define ICON_FA_GOOGLE "\xef\x86\xa0"	// U+f1a0 fa-google, categories: Brand Icons
#define ICON_FA_REDDIT "\xef\x86\xa1"	// U+f1a1 fa-reddit, categories: Brand Icons
#define ICON_FA_REDDIT_SQUARE "\xef\x86\xa2"	// U+f1a2 fa-reddit-square, categories: Brand Icons
#define ICON_FA_STUMBLEUPON_CIRCLE "\xef\x86\xa3"	// U+f1a3 fa-stumbleupon-circle, categories: Brand Icons
#define ICON_FA_STUMBLEUPON "\xef\x86\xa4"	// U+f1a4 fa-stumbleupon, categories: Brand Icons
#define ICON_FA_DELICIOUS "\xef\x86\xa5"	// U+f1a5 fa-delicious, categories: Brand Icons
#define ICON_FA_DIGG "\xef\x86\xa6"	// U+f1a6 fa-digg, categories: Brand Icons
#define ICON_FA_PIED_PIPER_PP "\xef\x86\xa7"	// U+f1a7 fa-pied-piper-pp, categories: Brand Icons
#define ICON_FA_PIED_PIPER_ALT "\xef\x86\xa8"	// U+f1a8 fa-pied-piper-alt, categories: Brand Icons
#define ICON_FA_DRUPAL "\xef\x86\xa9"	// U+f1a9 fa-drupal, categories: Brand Icons
#define ICON_FA_JOOMLA "\xef\x86\xaa"	// U+f1aa fa-joomla, categories: Brand Icons
#define ICON_FA_LANGUAGE "\xef\x86\xab"	// U+f1ab fa-language, filter: translate, categories: Web Application Icons
#define ICON_FA_FAX "\xef\x86\xac"	// U+f1ac fa-fax, categories: Web Application Icons
#define ICON_FA_BUILDING "\xef\x86\xad"	// U+f1ad fa-building, filter: work, business, apartment, office, company, categories: Web Application Icons
#define ICON_FA_CHILD "\xef\x86\xae"	// U+f1ae fa-child, categories: Web Application Icons
#define ICON_FA_PAW "\xef\x86\xb0"	// U+f1b0 fa-paw, filter: pet, categories: Web Application Icons
#define ICON_FA_SPOON "\xef\x86\xb1"	// U+f1b1 fa-spoon, categories: Web Application Icons
#define ICON_FA_CUBE "\xef\x86\xb2"	// U+f1b2 fa-cube, categories: Web Application Icons
#define ICON_FA_CUBES "\xef\x86\xb3"	// U+f1b3 fa-cubes, categories: Web Application Icons
#define ICON_FA_BEHANCE "\xef\x86\xb4"	// U+f1b4 fa-behance, categories: Brand Icons
#define ICON_FA_BEHANCE_SQUARE "\xef\x86\xb5"	// U+f1b5 fa-behance-square, categories: Brand Icons
#define ICON_FA_STEAM "\xef\x86\xb6"	// U+f1b6 fa-steam, categories: Brand Icons
#define ICON_FA_STEAM_SQUARE "\xef\x86\xb7"	// U+f1b7 fa-steam-square, categories: Brand Icons
#define ICON_FA_RECYCLE "\xef\x86\xb8"	// U+f1b8 fa-recycle, categories: Web Application Icons
#define ICON_FA_CAR "\xef\x86\xb9"	// U+f1b9 fa-car, aliases: fa-automobile, filter: vehicle, categories: Web Application Icons, Transportation Icons
#define ICON_FA_TAXI "\xef\x86\xba"	// U+f1ba fa-taxi, aliases: fa-cab, filter: vehicle, categories: Web Application Icons, Transportation Icons
#define ICON_FA_TREE "\xef\x86\xbb"	// U+f1bb fa-tree, categories: Web Application Icons
#define ICON_FA_SPOTIFY "\xef\x86\xbc"	// U+f1bc fa-spotify, categories: Brand Icons
#define ICON_FA_DEVIANTART "\xef\x86\xbd"	// U+f1bd fa-deviantart, categories: Brand Icons
#define ICON_FA_SOUNDCLOUD "\xef\x86\xbe"	// U+f1be fa-soundcloud, categories: Brand Icons
#define ICON_FA_DATABASE "\xef\x87\x80"	// U+f1c0 fa-database, categories: Web Application Icons
#define ICON_FA_FILE_PDF_O "\xef\x87\x81"	// U+f1c1 fa-file-pdf-o, categories: Web Application Icons, File Type Icons
#define ICON_FA_FILE_WORD_O "\xef\x87\x82"	// U+f1c2 fa-file-word-o, categories: Web Application Icons, File Type Icons
#define ICON_FA_FILE_EXCEL_O "\xef\x87\x83"	// U+f1c3 fa-file-excel-o, categories: Web Application Icons, File Type Icons
#define ICON_FA_FILE_POWERPOINT_O "\xef\x87\x84"	// U+f1c4 fa-file-powerpoint-o, categories: Web Application Icons, File Type Icons
#define ICON_FA_FILE_IMAGE_O "\xef\x87\x85"	// U+f1c5 fa-file-image-o, aliases: fa-file-photo-o, fa-file-picture-o, categories: Web Application Icons, File Type Icons
#define ICON_FA_FILE_ARCHIVE_O "\xef\x87\x86"	// U+f1c6 fa-file-archive-o, aliases: fa-file-zip-o, categories: Web Application Icons, File Type Icons
#define ICON_FA_FILE_AUDIO_O "\xef\x87\x87"	// U+f1c7 fa-file-audio-o, aliases: fa-file-sound-o, categories: Web Application Icons, File Type Icons
#define ICON_FA_FILE_VIDEO_O "\xef\x87\x88"	// U+f1c8 fa-file-video-o, aliases: fa-file-movie-o, categories: Web Application Icons, File Type Icons
#define ICON_FA_FILE_CODE_O "\xef\x87\x89"	// U+f1c9 fa-file-code-o, categories: Web Application Icons, File Type Icons
#define ICON_FA_VINE "\xef\x87\x8a"	// U+f1ca fa-vine, categories: Brand Icons
#define ICON_FA_CODEPEN "\xef\x87\x8b"	// U+f1cb fa-codepen, categories: Brand Icons
#define ICON_FA_JSFIDDLE "\xef\x87\x8c"	// U+f1cc fa-jsfiddle, categories: Brand Icons
#define ICON_FA_LIFE_RING "\xef\x87\x8d"	// U+f1cd fa-life-ring, aliases: fa-life-bouy, fa-life-buoy, fa-life-saver, fa-support, categories: Web Application Icons
#define ICON_FA_CIRCLE_O_NOTCH "\xef\x87\x8e"	// U+f1ce fa-circle-o-notch, categories: Web Application Icons, Spinner Icons
#define ICON_FA_REBEL "\xef\x87\x90"	// U+f1d0 fa-rebel, aliases: fa-ra, fa-resistance, categories: Brand Icons
#define ICON_FA_EMPIRE "\xef\x87\x91"	// U+f1d1 fa-empire, aliases: fa-ge, categories: Brand Icons
#define ICON_FA_GIT_SQUARE "\xef\x87\x92"	// U+f1d2 fa-git-square, categories: Brand Icons
#define ICON_FA_GIT "\xef\x87\x93"	// U+f1d3 fa-git, categories: Brand Icons
#define ICON_FA_HACKER_NEWS "\xef\x87\x94"	// U+f1d4 fa-hacker-news, aliases: fa-y-combinator-square, fa-yc-square, categories: Brand Icons
#define ICON_FA_TENCENT_WEIBO "\xef\x87\x95"	// U+f1d5 fa-tencent-weibo, categories: Brand Icons
#define ICON_FA_QQ "\xef\x87\x96"	// U+f1d6 fa-qq, categories: Brand Icons
#define ICON_FA_WEIXIN "\xef\x87\x97"	// U+f1d7 fa-weixin, aliases: fa-wechat, categories: Brand Icons
#define ICON_FA_PAPER_PLANE "\xef\x87\x98"	// U+f1d8 fa-paper-plane, aliases: fa-send, categories: Web Application Icons
#define ICON_FA_PAPER_PLANE_O "\xef\x87\x99"	// U+f1d9 fa-paper-plane-o, aliases: fa-send-o, categories: Web Application Icons
#define ICON_FA_HISTORY "\xef\x87\x9a"	// U+f1da fa-history, filter: recent, categories: Web Application Icons
#define ICON_FA_CIRCLE_THIN "\xef\x87\x9b"	// U+f1db fa-circle-thin, categories: Web Application Icons
#define ICON_FA_HEADER "\xef\x87\x9c"	// U+f1dc fa-header, filter: heading, categories: Text Editor Icons
#define ICON_FA_PARAGRAPH "\xef\x87\x9d"	// U+f1dd fa-paragraph, categories: Text Editor Icons
#define ICON_FA_SLIDERS "\xef\x87\x9e"	// U+f1de fa-sliders, filter: settings, categories: Web Application Icons
#define ICON_FA_SHARE_ALT "\xef\x87\xa0"	// U+f1e0 fa-share-alt, categories: Web Application Icons, Brand Icons
#define ICON_FA_SHARE_ALT_SQUARE "\xef\x87\xa1"	// U+f1e1 fa-share-alt-square, categories: Web Application Icons, Brand Icons
#define ICON_FA_BOMB "\xef\x87\xa2"	// U+f1e2 fa-bomb, categories: Web Application Icons
#define ICON_FA_FUTBOL_O "\xef\x87\xa3"	// U+f1e3 fa-futbol-o, aliases: fa-soccer-ball-o, categories: Web Application Icons
#define ICON_FA_TTY "\xef\x87\xa4"	// U+f1e4 fa-tty, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_BINOCULARS "\xef\x87\xa5"	// U+f1e5 fa-binoculars, categories: Web Application Icons
#define ICON_FA_PLUG "\xef\x87\xa6"	// U+f1e6 fa-plug, filter: power, connect, categories: Web Application Icons
#define ICON_FA_SLIDESHARE "\xef\x87\xa7"	// U+f1e7 fa-slideshare, categories: Brand Icons
#define ICON_FA_TWITCH "\xef\x87\xa8"	// U+f1e8 fa-twitch, categories: Brand Icons
#define ICON_FA_YELP "\xef\x87\xa9"	// U+f1e9 fa-yelp, categories: Brand Icons
#define ICON_FA_NEWSPAPER_O "\xef\x87\xaa"	// U+f1ea fa-newspaper-o, filter: press, categories: Web Application Icons
#define ICON_FA_WIFI "\xef\x87\xab"	// U+f1eb fa-wifi, categories: Web Application Icons
#define ICON_FA_CALCULATOR "\xef\x87\xac"	// U+f1ec fa-calculator, categories: Web Application Icons
#define ICON_FA_PAYPAL "\xef\x87\xad"	// U+f1ed fa-paypal, categories: Brand Icons, Payment Icons
#define ICON_FA_GOOGLE_WALLET "\xef\x87\xae"	// U+f1ee fa-google-wallet, categories: Brand Icons, Payment Icons
#define ICON_FA_CC_VISA "\xef\x87\xb0"	// U+f1f0 fa-cc-visa, categories: Brand Icons, Payment Icons
#define ICON_FA_CC_MASTERCARD "\xef\x87\xb1"	// U+f1f1 fa-cc-mastercard, categories: Brand Icons, Payment Icons
#define ICON_FA_CC_DISCOVER "\xef\x87\xb2"	// U+f1f2 fa-cc-discover, categories: Brand Icons, Payment Icons
#define ICON_FA_CC_AMEX "\xef\x87\xb3"	// U+f1f3 fa-cc-amex, filter: amex, categories: Brand Icons, Payment Icons
#define ICON_FA_CC_PAYPAL "\xef\x87\xb4"	// U+f1f4 fa-cc-paypal, categories: Brand Icons, Payment Icons
#define ICON_FA_CC_STRIPE "\xef\x87\xb5"	// U+f1f5 fa-cc-stripe, categories: Brand Icons, Payment Icons
#define ICON_FA_BELL_SLASH "\xef\x87\xb6"	// U+f1f6 fa-bell-slash, categories: Web Application Icons
#define ICON_FA_BELL_SLASH_O "\xef\x87\xb7"	// U+f1f7 fa-bell-slash-o, categories: Web Application Icons
#define ICON_FA_TRASH "\xef\x87\xb8"	// U+f1f8 fa-trash, filter: garbage, delete, remove, hide, categories: Web Application Icons
#define ICON_FA_COPYRIGHT "\xef\x87\xb9"	// U+f1f9 fa-copyright, categories: Web Application Icons
#define ICON_FA_AT "\xef\x87\xba"	// U+f1fa fa-at, filter: email, e-mail, categories: Web Application Icons
#define ICON_FA_EYEDROPPER "\xef\x87\xbb"	// U+f1fb fa-eyedropper, categories: Web Application Icons
#define ICON_FA_PAINT_BRUSH "\xef\x87\xbc"	// U+f1fc fa-paint-brush, categories: Web Application Icons
#define ICON_FA_BIRTHDAY_CAKE "\xef\x87\xbd"	// U+f1fd fa-birthday-cake, categories: Web Application Icons
#define ICON_FA_AREA_CHART "\xef\x87\xbe"	// U+f1fe fa-area-chart, filter: graph, analytics, statistics, categories: Web Application Icons, Chart Icons
#define ICON_FA_PIE_CHART "\xef\x88\x80"	// U+f200 fa-pie-chart, filter: graph, analytics, statistics, categories: Web Application Icons, Chart Icons
#define ICON_FA_LINE_CHART "\xef\x88\x81"	// U+f201 fa-line-chart, filter: graph, analytics, statistics, categories: Web Application Icons, Chart Icons
#define ICON_FA_LASTFM "\xef\x88\x82"	// U+f202 fa-lastfm, categories: Brand Icons
#define ICON_FA_LASTFM_SQUARE "\xef\x88\x83"	// U+f203 fa-lastfm-square, categories: Brand Icons
#define ICON_FA_TOGGLE_OFF "\xef\x88\x84"	// U+f204 fa-toggle-off, categories: Web Application Icons
#define ICON_FA_TOGGLE_ON "\xef\x88\x85"	// U+f205 fa-toggle-on, categories: Web Application Icons
#define ICON_FA_BICYCLE "\xef\x88\x86"	// U+f206 fa-bicycle, filter: vehicle, bike, categories: Web Application Icons, Transportation Icons
#define ICON_FA_BUS "\xef\x88\x87"	// U+f207 fa-bus, filter: vehicle, categories: Web Application Icons, Transportation Icons
#define ICON_FA_IOXHOST "\xef\x88\x88"	// U+f208 fa-ioxhost, categories: Brand Icons
#define ICON_FA_ANGELLIST "\xef\x88\x89"	// U+f209 fa-angellist, categories: Brand Icons
#define ICON_FA_CC "\xef\x88\x8a"	// U+f20a fa-cc, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_ILS "\xef\x88\x8b"	// U+f20b fa-ils, aliases: fa-shekel, fa-sheqel, categories: Currency Icons
#define ICON_FA_MEANPATH "\xef\x88\x8c"	// U+f20c fa-meanpath, categories: Brand Icons
#define ICON_FA_BUYSELLADS "\xef\x88\x8d"	// U+f20d fa-buysellads, categories: Brand Icons
#define ICON_FA_CONNECTDEVELOP "\xef\x88\x8e"	// U+f20e fa-connectdevelop, categories: Brand Icons
#define ICON_FA_DASHCUBE "\xef\x88\x90"	// U+f210 fa-dashcube, categories: Brand Icons
#define ICON_FA_FORUMBEE "\xef\x88\x91"	// U+f211 fa-forumbee, categories: Brand Icons
#define ICON_FA_LEANPUB "\xef\x88\x92"	// U+f212 fa-leanpub, categories: Brand Icons
#define ICON_FA_SELLSY "\xef\x88\x93"	// U+f213 fa-sellsy, categories: Brand Icons
#define ICON_FA_SHIRTSINBULK "\xef\x88\x94"	// U+f214 fa-shirtsinbulk, categories: Brand Icons
#define ICON_FA_SIMPLYBUILT "\xef\x88\x95"	// U+f215 fa-simplybuilt, categories: Brand Icons
#define ICON_FA_SKYATLAS "\xef\x88\x96"	// U+f216 fa-skyatlas, categories: Brand Icons
#define ICON_FA_CART_PLUS "\xef\x88\x97"	// U+f217 fa-cart-plus, filter: add, shopping, categories: Web Application Icons
#define ICON_FA_CART_ARROW_DOWN "\xef\x88\x98"	// U+f218 fa-cart-arrow-down, filter: shopping, categories: Web Application Icons
#define ICON_FA_DIAMOND "\xef\x88\x99"	// U+f219 fa-diamond, filter: gem, gemstone, categories: Web Application Icons
#define ICON_FA_SHIP "\xef\x88\x9a"	// U+f21a fa-ship, filter: boat, sea, categories: Web Application Icons, Transportation Icons
#define ICON_FA_USER_SECRET "\xef\x88\x9b"	// U+f21b fa-user-secret, filter: whisper, spy, incognito, privacy, categories: Web Application Icons
#define ICON_FA_MOTORCYCLE "\xef\x88\x9c"	// U+f21c fa-motorcycle, filter: vehicle, bike, categories: Web Application Icons, Transportation Icons
#define ICON_FA_STREET_VIEW "\xef\x88\x9d"	// U+f21d fa-street-view, filter: map, categories: Web Application Icons
#define ICON_FA_HEARTBEAT "\xef\x88\x9e"	// U+f21e fa-heartbeat, filter: ekg, categories: Web Application Icons, Medical Icons
#define ICON_FA_VENUS "\xef\x88\xa1"	// U+f221 fa-venus, filter: female, categories: Gender Icons
#define ICON_FA_MARS "\xef\x88\xa2"	// U+f222 fa-mars, filter: male, categories: Gender Icons
#define ICON_FA_MERCURY "\xef\x88\xa3"	// U+f223 fa-mercury, filter: transgender, categories: Gender Icons
#define ICON_FA_TRANSGENDER "\xef\x88\xa4"	// U+f224 fa-transgender, aliases: fa-intersex, categories: Gender Icons
#define ICON_FA_TRANSGENDER_ALT "\xef\x88\xa5"	// U+f225 fa-transgender-alt, categories: Gender Icons
#define ICON_FA_VENUS_DOUBLE "\xef\x88\xa6"	// U+f226 fa-venus-double, categories: Gender Icons
#define ICON_FA_MARS_DOUBLE "\xef\x88\xa7"	// U+f227 fa-mars-double, categories: Gender Icons
#define ICON_FA_VENUS_MARS "\xef\x88\xa8"	// U+f228 fa-venus-mars, categories: Gender Icons
#define ICON_FA_MARS_STROKE "\xef\x88\xa9"	// U+f229 fa-mars-stroke, categories: Gender Icons
#define ICON_FA_MARS_STROKE_V "\xef\x88\xaa"	// U+f22a fa-mars-stroke-v, categories: Gender Icons
#define ICON_FA_MARS_STROKE_H "\xef\x88\xab"	// U+f22b fa-mars-stroke-h, categories: Gender Icons
#define ICON_FA_NEUTER "\xef\x88\xac"	// U+f22c fa-neuter, categories: Gender Icons
#define ICON_FA_GENDERLESS "\xef\x88\xad"	// U+f22d fa-genderless, categories: Gender Icons
#define ICON_FA_FACEBOOK_OFFICIAL "\xef\x88\xb0"	// U+f230 fa-facebook-official, categories: Brand Icons
#define ICON_FA_PINTEREST_P "\xef\x88\xb1"	// U+f231 fa-pinterest-p, categories: Brand Icons
#define ICON_FA_WHATSAPP "\xef\x88\xb2"	// U+f232 fa-whatsapp, categories: Brand Icons
#define ICON_FA_SERVER "\xef\x88\xb3"	// U+f233 fa-server, categories: Web Application Icons
#define ICON_FA_USER_PLUS "\xef\x88\xb4"	// U+f234 fa-user-plus, filter: sign up, signup, categories: Web Application Icons
#define ICON_FA_USER_TIMES "\xef\x88\xb5"	// U+f235 fa-user-times, categories: Web Application Icons
#define ICON_FA_BED "\xef\x88\xb6"	// U+f236 fa-bed, aliases: fa-hotel, filter: travel, categories: Web Application Icons
#define ICON_FA_VIACOIN "\xef\x88\xb7"	// U+f237 fa-viacoin, categories: Currency Icons, Brand Icons
#define ICON_FA_TRAIN "\xef\x88\xb8"	// U+f238 fa-train, categories: Transportation Icons
#define ICON_FA_SUBWAY "\xef\x88\xb9"	// U+f239 fa-subway, categories: Transportation Icons
#define ICON_FA_MEDIUM "\xef\x88\xba"	// U+f23a fa-medium, categories: Brand Icons
#define ICON_FA_Y_COMBINATOR "\xef\x88\xbb"	// U+f23b fa-y-combinator, aliases: fa-yc, categories: Brand Icons
#define ICON_FA_OPTIN_MONSTER "\xef\x88\xbc"	// U+f23c fa-optin-monster, categories: Brand Icons
#define ICON_FA_OPENCART "\xef\x88\xbd"	// U+f23d fa-opencart, categories: Brand Icons
#define ICON_FA_EXPEDITEDSSL "\xef\x88\xbe"	// U+f23e fa-expeditedssl, categories: Brand Icons
#define ICON_FA_BATTERY_FULL "\xef\x89\x80"	// U+f240 fa-battery-full, aliases: fa-battery-4, fa-battery, filter: power, categories: Web Application Icons
#define ICON_FA_BATTERY_THREE_QUARTERS "\xef\x89\x81"	// U+f241 fa-battery-three-quarters, aliases: fa-battery-3, filter: power, categories: Web Application Icons
#define ICON_FA_BATTERY_HALF "\xef\x89\x82"	// U+f242 fa-battery-half, aliases: fa-battery-2, filter: power, categories: Web Application Icons
#define ICON_FA_BATTERY_QUARTER "\xef\x89\x83"	// U+f243 fa-battery-quarter, aliases: fa-battery-1, filter: power, categories: Web Application Icons
#define ICON_FA_BATTERY_EMPTY "\xef\x89\x84"	// U+f244 fa-battery-empty, aliases: fa-battery-0, filter: power, categories: Web Application Icons
#define ICON_FA_MOUSE_POINTER "\xef\x89\x85"	// U+f245 fa-mouse-pointer, categories: Web Application Icons
#define ICON_FA_I_CURSOR "\xef\x89\x86"	// U+f246 fa-i-cursor, categories: Web Application Icons
#define ICON_FA_OBJECT_GROUP "\xef\x89\x87"	// U+f247 fa-object-group, categories: Web Application Icons
#define ICON_FA_OBJECT_UNGROUP "\xef\x89\x88"	// U+f248 fa-object-ungroup, categories: Web Application Icons
#define ICON_FA_STICKY_NOTE "\xef\x89\x89"	// U+f249 fa-sticky-note, categories: Web Application Icons
#define ICON_FA_STICKY_NOTE_O "\xef\x89\x8a"	// U+f24a fa-sticky-note-o, categories: Web Application Icons
#define ICON_FA_CC_JCB "\xef\x89\x8b"	// U+f24b fa-cc-jcb, categories: Brand Icons, Payment Icons
#define ICON_FA_CC_DINERS_CLUB "\xef\x89\x8c"	// U+f24c fa-cc-diners-club, categories: Brand Icons, Payment Icons
#define ICON_FA_CLONE "\xef\x89\x8d"	// U+f24d fa-clone, filter: copy, categories: Web Application Icons
#define ICON_FA_BALANCE_SCALE "\xef\x89\x8e"	// U+f24e fa-balance-scale, categories: Web Application Icons
#define ICON_FA_HOURGLASS_O "\xef\x89\x90"	// U+f250 fa-hourglass-o, categories: Web Application Icons
#define ICON_FA_HOURGLASS_START "\xef\x89\x91"	// U+f251 fa-hourglass-start, aliases: fa-hourglass-1, categories: Web Application Icons
#define ICON_FA_HOURGLASS_HALF "\xef\x89\x92"	// U+f252 fa-hourglass-half, aliases: fa-hourglass-2, categories: Web Application Icons
#define ICON_FA_HOURGLASS_END "\xef\x89\x93"	// U+f253 fa-hourglass-end, aliases: fa-hourglass-3, categories: Web Application Icons
#define ICON_FA_HOURGLASS "\xef\x89\x94"	// U+f254 fa-hourglass, categories: Web Application Icons
#define ICON_FA_HAND_ROCK_O "\xef\x89\x95"	// U+f255 fa-hand-rock-o, aliases: fa-hand-grab-o, categories: Web Application Icons, Hand Icons
#define ICON_FA_HAND_PAPER_O "\xef\x89\x96"	// U+f256 fa-hand-paper-o, aliases: fa-hand-stop-o, filter: stop, categories: Web Application Icons, Hand Icons
#define ICON_FA_HAND_SCISSORS_O "\xef\x89\x97"	// U+f257 fa-hand-scissors-o, categories: Web Application Icons, Hand Icons
#define ICON_FA_HAND_LIZARD_O "\xef\x89\x98"	// U+f258 fa-hand-lizard-o, categories: Web Application Icons, Hand Icons
#define ICON_FA_HAND_SPOCK_O "\xef\x89\x99"	// U+f259 fa-hand-spock-o, categories: Web Application Icons, Hand Icons
#define ICON_FA_HAND_POINTER_O "\xef\x89\x9a"	// U+f25a fa-hand-pointer-o, categories: Web Application Icons, Hand Icons
#define ICON_FA_HAND_PEACE_O "\xef\x89\x9b"	// U+f25b fa-hand-peace-o, categories: Web Application Icons, Hand Icons
#define ICON_FA_TRADEMARK "\xef\x89\x9c"	// U+f25c fa-trademark, categories: Web Application Icons
#define ICON_FA_REGISTERED "\xef\x89\x9d"	// U+f25d fa-registered, categories: Web Application Icons
#define ICON_FA_CREATIVE_COMMONS "\xef\x89\x9e"	// U+f25e fa-creative-commons, categories: Web Application Icons
#define ICON_FA_GG "\xef\x89\xa0"	// U+f260 fa-gg, categories: Currency Icons, Brand Icons
#define ICON_FA_GG_CIRCLE "\xef\x89\xa1"	// U+f261 fa-gg-circle, categories: Currency Icons, Brand Icons
#define ICON_FA_TRIPADVISOR "\xef\x89\xa2"	// U+f262 fa-tripadvisor, categories: Brand Icons
#define ICON_FA_ODNOKLASSNIKI "\xef\x89\xa3"	// U+f263 fa-odnoklassniki, categories: Brand Icons
#define ICON_FA_ODNOKLASSNIKI_SQUARE "\xef\x89\xa4"	// U+f264 fa-odnoklassniki-square, categories: Brand Icons
#define ICON_FA_GET_POCKET "\xef\x89\xa5"	// U+f265 fa-get-pocket, categories: Brand Icons
#define ICON_FA_WIKIPEDIA_W "\xef\x89\xa6"	// U+f266 fa-wikipedia-w, categories: Brand Icons
#define ICON_FA_SAFARI "\xef\x89\xa7"	// U+f267 fa-safari, filter: browser, categories: Brand Icons
#define ICON_FA_CHROME "\xef\x89\xa8"	// U+f268 fa-chrome, filter: browser, categories: Brand Icons
#define ICON_FA_FIREFOX "\xef\x89\xa9"	// U+f269 fa-firefox, filter: browser, categories: Brand Icons
#define ICON_FA_OPERA "\xef\x89\xaa"	// U+f26a fa-opera, categories: Brand Icons
#define ICON_FA_INTERNET_EXPLORER "\xef\x89\xab"	// U+f26b fa-internet-explorer, filter: browser, ie, categories: Brand Icons
#define ICON_FA_TELEVISION "\xef\x89\xac"	// U+f26c fa-television, aliases: fa-tv, filter: display, computer, monitor, categories: Web Application Icons
#define ICON_FA_CONTAO "\xef\x89\xad"	// U+f26d fa-contao, categories: Brand Icons
#define ICON_FA_500PX "\xef\x89\xae"	// U+f26e fa-500px, categories: Brand Icons
#define ICON_FA_AMAZON "\xef\x89\xb0"	// U+f270 fa-amazon, categories: Brand Icons
#define ICON_FA_CALENDAR_PLUS_O "\xef\x89\xb1"	// U+f271 fa-calendar-plus-o, categories: Web Application Icons
#define ICON_FA_CALENDAR_MINUS_O "\xef\x89\xb2"	// U+f272 fa-calendar-minus-o, categories: Web Application Icons
#define ICON_FA_CALENDAR_TIMES_O "\xef\x89\xb3"	// U+f273 fa-calendar-times-o, categories: Web Application Icons
#define ICON_FA_CALENDAR_CHECK_O "\xef\x89\xb4"	// U+f274 fa-calendar-check-o, filter: ok, categories: Web Application Icons
#define ICON_FA_INDUSTRY "\xef\x89\xb5"	// U+f275 fa-industry, filter: factory, categories: Web Application Icons
#define ICON_FA_MAP_PIN "\xef\x89\xb6"	// U+f276 fa-map-pin, categories: Web Application Icons
#define ICON_FA_MAP_SIGNS "\xef\x89\xb7"	// U+f277 fa-map-signs, categories: Web Application Icons
#define ICON_FA_MAP_O "\xef\x89\xb8"	// U+f278 fa-map-o, categories: Web Application Icons
#define ICON_FA_MAP "\xef\x89\xb9"	// U+f279 fa-map, categories: Web Application Icons
#define ICON_FA_COMMENTING "\xef\x89\xba"	// U+f27a fa-commenting, filter: speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation, categories: Web Application Icons
#define ICON_FA_COMMENTING_O "\xef\x89\xbb"	// U+f27b fa-commenting-o, filter: speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation, categories: Web Application Icons
#define ICON_FA_HOUZZ "\xef\x89\xbc"	// U+f27c fa-houzz, categories: Brand Icons
#define ICON_FA_VIMEO "\xef\x89\xbd"	// U+f27d fa-vimeo, categories: Brand Icons
#define ICON_FA_BLACK_TIE "\xef\x89\xbe"	// U+f27e fa-black-tie, categories: Brand Icons
#define ICON_FA_FONTICONS "\xef\x8a\x80"	// U+f280 fa-fonticons, categories: Brand Icons
#define ICON_FA_REDDIT_ALIEN "\xef\x8a\x81"	// U+f281 fa-reddit-alien, categories: Brand Icons
#define ICON_FA_EDGE "\xef\x8a\x82"	// U+f282 fa-edge, filter: browser, ie, categories: Brand Icons
#define ICON_FA_CREDIT_CARD_ALT "\xef\x8a\x83"	// U+f283 fa-credit-card-alt, filter: money, buy, debit, checkout, purchase, payment, credit card, categories: Payment Icons, Web Application Icons
#define ICON_FA_CODIEPIE "\xef\x8a\x84"	// U+f284 fa-codiepie, categories: Brand Icons
#define ICON_FA_MODX "\xef\x8a\x85"	// U+f285 fa-modx, categories: Brand Icons
#define ICON_FA_FORT_AWESOME "\xef\x8a\x86"	// U+f286 fa-fort-awesome, categories: Brand Icons
#define ICON_FA_USB "\xef\x8a\x87"	// U+f287 fa-usb, categories: Brand Icons
#define ICON_FA_PRODUCT_HUNT "\xef\x8a\x88"	// U+f288 fa-product-hunt, categories: Brand Icons
#define ICON_FA_MIXCLOUD "\xef\x8a\x89"	// U+f289 fa-mixcloud, categories: Brand Icons
#define ICON_FA_SCRIBD "\xef\x8a\x8a"	// U+f28a fa-scribd, categories: Brand Icons
#define ICON_FA_PAUSE_CIRCLE "\xef\x8a\x8b"	// U+f28b fa-pause-circle, categories: Video Player Icons
#define ICON_FA_PAUSE_CIRCLE_O "\xef\x8a\x8c"	// U+f28c fa-pause-circle-o, categories: Video Player Icons
#define ICON_FA_STOP_CIRCLE "\xef\x8a\x8d"	// U+f28d fa-stop-circle, categories: Video Player Icons
#define ICON_FA_STOP_CIRCLE_O "\xef\x8a\x8e"	// U+f28e fa-stop-circle-o, categories: Video Player Icons
#define ICON_FA_SHOPPING_BAG "\xef\x8a\x90"	// U+f290 fa-shopping-bag, categories: Web Application Icons
#define ICON_FA_SHOPPING_BASKET "\xef\x8a\x91"	// U+f291 fa-shopping-basket, categories: Web Application Icons
#define ICON_FA_HASHTAG "\xef\x8a\x92"	// U+f292 fa-hashtag, categories: Web Application Icons
#define ICON_FA_BLUETOOTH "\xef\x8a\x93"	// U+f293 fa-bluetooth, categories: Web Application Icons, Brand Icons
#define ICON_FA_BLUETOOTH_B "\xef\x8a\x94"	// U+f294 fa-bluetooth-b, categories: Web Application Icons, Brand Icons
#define ICON_FA_PERCENT "\xef\x8a\x95"	// U+f295 fa-percent, categories: Web Application Icons
#define ICON_FA_GITLAB "\xef\x8a\x96"	// U+f296 fa-gitlab, categories: Brand Icons
#define ICON_FA_WPBEGINNER "\xef\x8a\x97"	// U+f297 fa-wpbeginner, categories: Brand Icons
#define ICON_FA_WPFORMS "\xef\x8a\x98"	// U+f298 fa-wpforms, categories: Brand Icons
#define ICON_FA_ENVIRA "\xef\x8a\x99"	// U+f299 fa-envira, filter: leaf, categories: Brand Icons
#define ICON_FA_UNIVERSAL_ACCESS "\xef\x8a\x9a"	// U+f29a fa-universal-access, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_WHEELCHAIR_ALT "\xef\x8a\x9b"	// U+f29b fa-wheelchair-alt, filter: handicap, person, categories: Web Application Icons, Medical Icons, Transportation Icons, Accessibility Icons
#define ICON_FA_QUESTION_CIRCLE_O "\xef\x8a\x9c"	// U+f29c fa-question-circle-o, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_BLIND "\xef\x8a\x9d"	// U+f29d fa-blind, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_AUDIO_DESCRIPTION "\xef\x8a\x9e"	// U+f29e fa-audio-description, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_VOLUME_CONTROL_PHONE "\xef\x8a\xa0"	// U+f2a0 fa-volume-control-phone, filter: telephone, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_BRAILLE "\xef\x8a\xa1"	// U+f2a1 fa-braille, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_ASSISTIVE_LISTENING_SYSTEMS "\xef\x8a\xa2"	// U+f2a2 fa-assistive-listening-systems, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_AMERICAN_SIGN_LANGUAGE_INTERPRETING "\xef\x8a\xa3"	// U+f2a3 fa-american-sign-language-interpreting, aliases: fa-asl-interpreting, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_DEAF "\xef\x8a\xa4"	// U+f2a4 fa-deaf, aliases: fa-deafness, fa-hard-of-hearing, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_GLIDE "\xef\x8a\xa5"	// U+f2a5 fa-glide, categories: Brand Icons
#define ICON_FA_GLIDE_G "\xef\x8a\xa6"	// U+f2a6 fa-glide-g, categories: Brand Icons
#define ICON_FA_SIGN_LANGUAGE "\xef\x8a\xa7"	// U+f2a7 fa-sign-language, aliases: fa-signing, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_LOW_VISION "\xef\x8a\xa8"	// U+f2a8 fa-low-vision, categories: Web Application Icons, Accessibility Icons
#define ICON_FA_VIADEO "\xef\x8a\xa9"	// U+f2a9 fa-viadeo, categories: Brand Icons
#define ICON_FA_VIADEO_SQUARE "\xef\x8a\xaa"	// U+f2aa fa-viadeo-square, categories: Brand Icons
#define ICON_FA_SNAPCHAT "\xef\x8a\xab"	// U+f2ab fa-snapchat, categories: Brand Icons
#define ICON_FA_SNAPCHAT_GHOST "\xef\x8a\xac"	// U+f2ac fa-snapchat-ghost, categories: Brand Icons
#define ICON_FA_SNAPCHAT_SQUARE "\xef\x8a\xad"	// U+f2ad fa-snapchat-square, categories: Brand Icons
#define ICON_FA_PIED_PIPER "\xef\x8a\xae"	// U+f2ae fa-pied-piper, categories: Brand Icons
#define ICON_FA_FIRST_ORDER "\xef\x8a\xb0"	// U+f2b0 fa-first-order, categories: Brand Icons
#define ICON_FA_YOAST "\xef\x8a\xb1"	// U+f2b1 fa-yoast, categories: Brand Icons
#define ICON_FA_THEMEISLE "\xef\x8a\xb2"	// U+f2b2 fa-themeisle, categories: Brand Icons
#define ICON_FA_GOOGLE_PLUS_OFFICIAL "\xef\x8a\xb3"	// U+f2b3 fa-google-plus-official, aliases: fa-google-plus-circle, categories: Brand Icons
#define ICON_FA_FONT_AWESOME "\xef\x8a\xb4"	// U+f2b4 fa-font-awesome, aliases: fa-fa, categories: Brand Icons
#define ICON_FA_HANDSHAKE_O "\xef\x8a\xb5"	// U+f2b5 fa-handshake-o, categories: Web Application Icons
#define ICON_FA_ENVELOPE_OPEN "\xef\x8a\xb6"	// U+f2b6 fa-envelope-open, filter: email, e-mail, letter, support, mail, message, notification, categories: Web Application Icons
#define ICON_FA_ENVELOPE_OPEN_O "\xef\x8a\xb7"	// U+f2b7 fa-envelope-open-o, filter: email, e-mail, letter, support, mail, message, notification, categories: Web Application Icons
#define ICON_FA_LINODE "\xef\x8a\xb8"	// U+f2b8 fa-linode, categories: Brand Icons
#define ICON_FA_ADDRESS_BOOK "\xef\x8a\xb9"	// U+f2b9 fa-address-book, categories: Web Application Icons
#define ICON_FA_ADDRESS_BOOK_O "\xef\x8a\xba"	// U+f2ba fa-address-book-o, categories: Web Application Icons
#define ICON_FA_ADDRESS_CARD "\xef\x8a\xbb"	// U+f2bb fa-address-card, aliases: fa-vcard, categories: Web Application Icons
#define ICON_FA_ADDRESS_CARD_O "\xef\x8a\xbc"	// U+f2bc fa-address-card-o, aliases: fa-vcard-o, categories: Web Application Icons
#define ICON_FA_USER_CIRCLE "\xef\x8a\xbd"	// U+f2bd fa-user-circle, categories: Web Application Icons
#define ICON_FA_USER_CIRCLE_O "\xef\x8a\xbe"	// U+f2be fa-user-circle-o, categories: Web Application Icons
#define ICON_FA_USER_O "\xef\x8b\x80"	// U+f2c0 fa-user-o, categories: Web Application Icons
#define ICON_FA_ID_BADGE "\xef\x8b\x81"	// U+f2c1 fa-id-badge, categories: Web Application Icons
#define ICON_FA_ID_CARD "\xef\x8b\x82"	// U+f2c2 fa-id-card, aliases: fa-drivers-license, categories: Web Application Icons
#define ICON_FA_ID_CARD_O "\xef\x8b\x83"	// U+f2c3 fa-id-card-o, aliases: fa-drivers-license-o, categories: Web Application Icons
#define ICON_FA_QUORA "\xef\x8b\x84"	// U+f2c4 fa-quora, categories: Brand Icons
#define ICON_FA_FREE_CODE_CAMP "\xef\x8b\x85"	// U+f2c5 fa-free-code-camp, categories: Brand Icons
#define ICON_FA_TELEGRAM "\xef\x8b\x86"	// U+f2c6 fa-telegram, categories: Brand Icons
#define ICON_FA_THERMOMETER_FULL "\xef\x8b\x87"	// U+f2c7 fa-thermometer-full, aliases: fa-thermometer-4, fa-thermometer, categories: Web Application Icons
#define ICON_FA_THERMOMETER_THREE_QUARTERS "\xef\x8b\x88"	// U+f2c8 fa-thermometer-three-quarters, aliases: fa-thermometer-3, categories: Web Application Icons
#define ICON_FA_THERMOMETER_HALF "\xef\x8b\x89"	// U+f2c9 fa-thermometer-half, aliases: fa-thermometer-2, categories: Web Application Icons
#define ICON_FA_THERMOMETER_QUARTER "\xef\x8b\x8a"	// U+f2ca fa-thermometer-quarter, aliases: fa-thermometer-1, categories: Web Application Icons
#define ICON_FA_THERMOMETER_EMPTY "\xef\x8b\x8b"	// U+f2cb fa-thermometer-empty, aliases: fa-thermometer-0, categories: Web Application Icons
#define ICON_FA_SHOWER "\xef\x8b\x8c"	// U+f2cc fa-shower, categories: Web Application Icons
#define ICON_FA_BATH "\xef\x8b\x8d"	// U+f2cd fa-bath, aliases: fa-bathtub, fa-s15, categories: Web Application Icons
#define ICON_FA_PODCAST "\xef\x8b\x8e"	// U+f2ce fa-podcast, categories: Web Application Icons
#define ICON_FA_WINDOW_MAXIMIZE "\xef\x8b\x90"	// U+f2d0 fa-window-maximize, categories: Web Application Icons
#define ICON_FA_WINDOW_MINIMIZE "\xef\x8b\x91"	// U+f2d1 fa-window-minimize, categories: Web Application Icons
#define ICON_FA_WINDOW_RESTORE "\xef\x8b\x92"	// U+f2d2 fa-window-restore, categories: Web Application Icons
#define ICON_FA_WINDOW_CLOSE "\xef\x8b\x93"	// U+f2d3 fa-window-close, aliases: fa-times-rectangle, categories: Web Application Icons
#define ICON_FA_WINDOW_CLOSE_O "\xef\x8b\x94"	// U+f2d4 fa-window-close-o, aliases: fa-times-rectangle-o, categories: Web Application Icons
#define ICON_FA_BANDCAMP "\xef\x8b\x95"	// U+f2d5 fa-bandcamp, categories: Brand Icons
#define ICON_FA_GRAV "\xef\x8b\x96"	// U+f2d6 fa-grav, categories: Brand Icons
#define ICON_FA_ETSY "\xef\x8b\x97"	// U+f2d7 fa-etsy, categories: Brand Icons
#define ICON_FA_IMDB "\xef\x8b\x98"	// U+f2d8 fa-imdb, categories: Brand Icons
#define ICON_FA_RAVELRY "\xef\x8b\x99"	// U+f2d9 fa-ravelry, categories: Brand Icons
#define ICON_FA_EERCAST "\xef\x8b\x9a"	// U+f2da fa-eercast, categories: Brand Icons
#define ICON_FA_MICROCHIP "\xef\x8b\x9b"	// U+f2db fa-microchip, categories: Web Application Icons
#define ICON_FA_SNOWFLAKE_O "\xef\x8b\x9c"	// U+f2dc fa-snowflake-o, categories: Web Application Icons
#define ICON_FA_SUPERPOWERS "\xef\x8b\x9d"	// U+f2dd fa-superpowers, categories: Brand Icons
#define ICON_FA_WPEXPLORER "\xef\x8b\x9e"	// U+f2de fa-wpexplorer, categories: Brand Icons
#define ICON_FA_MEETUP "\xef\x8b\xa0"	// U+f2e0 fa-meetup, categories: Brand Icons
