const fetch = require("node-fetch");
const YAML = require("yaml");
const fs = require("fs");

const MetadataURL =
  "https://github.com/FortAwesome/Font-Awesome/raw/4.x/src/icons.yml";

function formatName(aName) {
  const words = aName.split("-");
  words.forEach((word, idx, arr) => {
    if (!isNaN(word.charAt(0)))
      // add _ prefix if name begin with a number
      word = "_" + word;
    arr[idx] = word.charAt(0).toUpperCase() + word.slice(1);
  });
  return words.join("");
}

function formatUnicode(aUnicode) {
  return `\\u{${aUnicode}}`;
}

function dumpAsLuaTable(aIcons) {
  let lua_str = "";
  lua_str +=
    "-- Generated by https://github.com/Nats-ji/FontAwesomeLuaTable for LuaJLT and Lua 5.3+\n";
  lua_str += `-- from ${MetadataURL}\n`;
  lua_str +=
    "-- for use with https://github.com/FortAwesome/Font-Awesome/blob/4.x/fonts/fontawesome-webfont.ttf\n";
  lua_str += "local IconGlyphs = {\n";
  for (const icon in aIcons) {
    lua_str += `  ${icon} = "${aIcons[icon]}",\n`;
  }
  lua_str += "}\n";
  lua_str += "return IconGlyphs\n";
  return lua_str;
}

function dumpLuaType(aIcons) {
  let lua_str = "";
  lua_str +=
    "-- Generated by https://github.com/Nats-ji/FontAwesomeLuaTable for VSCode extension sumneko.lua\n";
  lua_str += `-- from ${MetadataURL}\n`;
  lua_str +=
    "-- for use with https://github.com/FortAwesome/Font-Awesome/blob/4.x/fonts/fontawesome-webfont.ttf\n";
  lua_str += "---@meta\n";
  lua_str += "---@diagnostic disable\n\n";
  lua_str += "---@class IconGlyphs\n";
  for (const icon in aIcons) {
    lua_str += `---@field ${icon} "${aIcons[icon]}"\n`;
  }
  lua_str += "IconGlyphs = {}\n";
  return lua_str;
}

async function main() {
  // fetch metadata
  const response = await fetch(MetadataURL);
  const data = await response.text();
  const metadata = YAML.parse(data);

  // parse metadata
  const icons = {};
  for (const icon of metadata.icons) {
    icons[formatName(icon.id)] = formatUnicode(icon.unicode);
  }

  // generate lua file
  fs.mkdirSync("lua", { recursive: true });
  fs.writeFileSync("lua/IconsFontAwesome4.lua", dumpAsLuaTable(icons));
  fs.writeFileSync("lua/IconsFontAwesome4.type.lua", dumpLuaType(icons));
  console.log("Done");
}

main();
